export const DDROptions = {
  16: [
    {
      id: "early_late",
      name: "Fast/Slow Display",
      help: "Enable or disable displaying of Fast/Slow",
      type: "Boolean",
    },
    {
      id: "combo",
      name: "Combo Position",
      help: "Change order of the combo and notes",
      type: "Boolean",
    },
    {
      id: "weight",
      name: "Weight (kg)",
      help: "Set your weight for in-game workout mode. Input is kg multiplied by 10. EX: 100lbs -> ~45kg -> 4500. This will be fixed soon™️.",
      type: "Number",
    },
    {
      id: "character",
      name: "Character",
      help: "Select your character",
      type: "Array",
      options: [
        { id: 0, label: "All Character Random" },
        { id: 1, label: "Male Random" },
        { id: 2, label: "Female Random" },
        { id: 3, label: "Yuni" },
        { id: 4, label: "Rage" },
        { id: 5, label: "Afro" },
        { id: 6, label: "Jenny" },
        { id: 7, label: "Emi" },
        { id: 8, label: "Baby-Lon" },
        { id: 9, label: "Gus" },
        { id: 10, label: "Ruby" },
        { id: 11, label: "Alice" },
        { id: 12, label: "Julio" },
        { id: 13, label: "Bonnie" },
        { id: 14, label: "Zero" },
        { id: 15, label: "Rinon" },
        { id: 16, label: "Ryusei Emi" },
        { id: 17, label: "Ryusei Alice" },
        { id: 18, label: "Ryusei Rinon" },
        { id: 19, label: "KAC Yuni" },
        { id: 20, label: "Dark Rinon" },
        { id: 21, label: "Victory Concent" },
        { id: 22, label: "Geisha Zukin" },
        { id: 23, label: "Green Pix" },
        { id: 24, label: "Ace Emi" },
        { id: 25, label: "X2 Yuni" },
        { id: 26, label: "X2 Rage" },
        { id: 27, label: "X2 Afro" },
        { id: 28, label: "X2 Jenny" },
      ],
    },
    {
      id: "arrowskin",
      name: "Arrow Skin",
      help: "Set your arrow skin",
      type: "Array",
      options: [
        { id: 0, label: "Normal" },
        { id: 1, label: "New" },
        { id: 2, label: "Classic" },
        { id: 3, label: "Cyber" },
        { id: 4, label: "Medium" },
        { id: 5, label: "Small" },
        { id: 6, label: "Dot" },
      ],
    },
    {
      id: "guidelines",
      name: "Guidelines",
      help: "Set the guideline style",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Border" },
        { id: 2, label: "Center" },
      ],
    },
    {
      id: "filter",
      name: "Filter",
      help: "Set the filter intensity",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Dark" },
        { id: 2, label: "Darker" },
        { id: 3, label: "Darkest" },
      ],
    },
  ],
  17: [
    {
      id: "early_late",
      name: "Fast/Slow Display",
      help: "Enable or disable displaying of Fast/Slow",
      type: "Boolean",
    },
    {
      id: "combo",
      name: "Combo Position",
      help: "Change order of the combo and notes",
      type: "Boolean",
    },
    {
      id: "weight",
      name: "Weight (kg)",
      help: "Set your weight for in-game workout mode",
      type: "Number",
    },
    {
      id: "character",
      name: "Character",
      help: "Select your character",
      type: "Array",
      options: [
        { id: 0, label: "All Character Random" },
        { id: 1, label: "Male Random" },
        { id: 2, label: "Female Random" },
        { id: 3, label: "Yuni" },
        { id: 4, label: "Rage" },
        { id: 5, label: "Afro" },
        { id: 6, label: "Jenny" },
        { id: 7, label: "Emi" },
        { id: 8, label: "Baby-Lon" },
        { id: 9, label: "Gus" },
        { id: 10, label: "Ruby" },
        { id: 11, label: "Alice" },
        { id: 12, label: "Julio" },
        { id: 13, label: "Bonnie" },
        { id: 14, label: "Zero" },
        { id: 15, label: "Rinon" },
      ],
    },
    {
      id: "arrowskin",
      name: "Arrow Skin",
      help: "Set your arrow skin",
      type: "Array",
      options: [
        { id: 0, label: "Normal" },
        { id: 1, label: "New" },
        { id: 2, label: "Classic" },
        { id: 3, label: "Cyber" },
        { id: 4, label: "Medium" },
        { id: 5, label: "Small" },
        { id: 6, label: "Dot" },
      ],
    },
    {
      id: "guidelines",
      name: "Guidelines",
      help: "Set the guideline style",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Border" },
        { id: 2, label: "Center" },
      ],
    },
    {
      id: "filter",
      name: "Filter",
      help: "Set the filter intensity",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Dark" },
        { id: 2, label: "Darker" },
        { id: 3, label: "Darkest" },
      ],
    },
  ],
  18: [
    {
      id: "early_late",
      name: "Fast/Slow Display",
      help: "Enable or disable displaying of Fast/Slow",
      type: "Boolean",
    },
    {
      id: "combo",
      name: "Combo Position",
      help: "Change order of the combo and notes",
      type: "Boolean",
    },
    {
      id: "weight",
      name: "Weight (kg)",
      help: "Set your weight for in-game workout mode",
      type: "Number",
    },
    {
      id: "character",
      name: "Character",
      help: "Select your character",
      type: "Array",
      options: [
        { id: 0, label: "All Character Random" },
        { id: 1, label: "Male Random" },
        { id: 2, label: "Female Random" },
        { id: 3, label: "Yuni" },
        { id: 4, label: "Rage" },
        { id: 5, label: "Afro" },
        { id: 6, label: "Jenny" },
        { id: 7, label: "Emi" },
        { id: 8, label: "Baby-Lon" },
        { id: 9, label: "Gus" },
        { id: 10, label: "Ruby" },
        { id: 11, label: "Alice" },
        { id: 12, label: "Julio" },
        { id: 13, label: "Bonnie" },
        { id: 14, label: "Zero" },
        { id: 15, label: "Rinon" },
      ],
    },
    {
      id: "arrowskin",
      name: "Arrow Skin",
      help: "Set your arrow skin",
      type: "Array",
      options: [
        { id: 0, label: "Normal" },
        { id: 1, label: "New" },
        { id: 2, label: "Classic" },
        { id: 3, label: "Cyber" },
        { id: 4, label: "Medium" },
        { id: 5, label: "Small" },
        { id: 6, label: "Dot" },
      ],
    },
    {
      id: "guidelines",
      name: "Guidelines",
      help: "Set the guideline style",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Border" },
        { id: 2, label: "Center" },
      ],
    },
    {
      id: "filter",
      name: "Filter",
      help: "Set the filter intensity",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Dark" },
        { id: 2, label: "Darker" },
        { id: 3, label: "Darkest" },
      ],
    },
  ],
  19: [
    {
      id: "early_late",
      name: "Fast/Slow Display",
      help: "Enable or disable displaying of Fast/Slow",
      type: "Boolean",
    },
    {
      id: "combo",
      name: "Combo Position",
      help: "Change order of the combo and notes",
      type: "Boolean",
    },
    {
      id: "weight",
      name: "Weight (kg)",
      help: "Set your weight for in-game workout mode",
      type: "Number",
    },
    {
      id: "character",
      name: "Character",
      help: "Select your character",
      type: "Array",
      options: [
        { id: 0, label: "All Character Random" },
        { id: 1, label: "Male Random" },
        { id: 2, label: "Female Random" },
        { id: 3, label: "Yuni" },
        { id: 4, label: "Rage" },
        { id: 5, label: "Afro" },
        { id: 6, label: "Jenny" },
        { id: 7, label: "Emi" },
        { id: 8, label: "Baby-Lon" },
        { id: 9, label: "Gus" },
        { id: 10, label: "Ruby" },
        { id: 11, label: "Alice" },
        { id: 12, label: "Julio" },
        { id: 13, label: "Bonnie" },
        { id: 14, label: "Zero" },
        { id: 15, label: "Rinon" },
      ],
    },
    {
      id: "arrowskin",
      name: "Arrow Skin",
      help: "Set your arrow skin",
      type: "Array",
      options: [
        { id: 0, label: "Normal" },
        { id: 1, label: "New" },
        { id: 2, label: "Classic" },
        { id: 3, label: "Cyber" },
        { id: 4, label: "Medium" },
        { id: 5, label: "Small" },
        { id: 6, label: "Dot" },
      ],
    },
    {
      id: "guidelines",
      name: "Guidelines",
      help: "Set the guideline style",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Border" },
        { id: 2, label: "Center" },
      ],
    },
    {
      id: "opt_appearance",
      name: "Appearance Option",
      help: "Set your appearance option",
      type: "Array",
      options: [
        { id: 0, label: "Normal" },
        { id: 1, label: "Hidden" },
        { id: 2, label: "Sudden" },
        { id: 3, label: "Hidden +" },
        { id: 4, label: "Sudden +" },
        { id: 5, label: "Hidden & Sudden +" },
        { id: 6, label: "Stealth" },
      ],
    },
    {
      id: "filter",
      name: "Filter",
      help: "Set the filter intensity",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Dark" },
        { id: 2, label: "Darker" },
        { id: 3, label: "Darkest" },
      ],
    },
    {
      id: "bpl_flag",
      name: "BPL Flag",
      help: "Choose your BPL flag",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Apina Vrames" },
        { id: 2, label: "Gigo" },
        { id: 3, label: "Game Panic" },
        { id: 4, label: "Silk Hat" },
        { id: 5, label: "SUPER NOVA Tohoku" },
        { id: 6, label: "TradZ" },
        { id: 7, label: "ROUND 1" },
        { id: 8, label: "Leisure Land" },
      ],
    },
  ],
  20: [
    {
      id: "weight",
      name: "Weight (kg)",
      help: "Set your weight for in-game calorie counting",
      type: "Number",
    },
    {
      id: "customize.1_0",
      name: "Appeal Board",
      help: "Choose your appeal board",
      type: "Array",
      options: [
        { id: 1, label: "プレーン (パターン1)" },
        { id: 2, label: "プレーン (パターン2)" },
        { id: 3, label: "プレーン (パターン3)" },
        { id: 4, label: "EMI" },
        { id: 5, label: "RAGE" },
        { id: 6, label: "ALICE" },
        { id: 7, label: "BABY-LON" },
        { id: 8, label: "みゅ、みゅ、Müllる" },
        { id: 9, label: "Astrogazer" },
        { id: 10, label: "Don't Stop The HYPERCORE" },
        { id: 11, label: "Steps for Victory" },
        { id: 12, label: "メテオラ-meteor" },
        { id: 13, label: "Wizards!" },
        { id: 14, label: "THUNDERSTRIKE" },
        { id: 15, label: "blue anthem" },
        { id: 16, label: "Get Into The Groove feat.WaMi" },
        { id: 17, label: "ESPRIT ONE" },
        { id: 18, label: "Mighty Beat Monsterz" },
        { id: 19, label: "ひなビタ♪" },
        { id: 20, label: "ここなつ" },
        { id: 21, label: "山形まり花" },
        { id: 22, label: "和泉一舞" },
        { id: 23, label: "春日咲子" },
        { id: 24, label: "芽兎めう" },
        { id: 25, label: "霜月凛" },
        { id: 26, label: "東雲夏陽" },
        { id: 27, label: "東雲心菜" },
        { id: 28, label: "久領堤纒" },
        { id: 29, label: "星見日向" },
        { id: 30, label: "YUNI" },
        { id: 31, label: "AKIRA" },
        { id: 32, label: "Destination" },
        { id: 33, label: "HyperTwist" },
        { id: 34, label: "Cosy Catastrophe" },
        { id: 35, label: "New York EVOLVED" },
        { id: 36, label: "小舞桜 (Amado Kon)" },
        { id: 37, label: "小舞桜 (Komai Sakura)" },
        { id: 38, label: "Deep tenDon Reflex" },
        { id: 39, label: "ROCK THE PARTY" },
        { id: 40, label: "エンドルフィン" },
        { id: 41, label: "TSUGARU (春のコナステ大感謝祭2024)" },
        { id: 42, label: "GRACE (春のコナステ大感謝祭2024)" },
        { id: 43, label: "RINON (春のコナステ大感謝祭2024)" },
        { id: 44, label: "MIMI (春のコナステ大感謝祭2024)" },
        { id: 45, label: "RIO (春のコナステ大感謝祭2024)" },
        { id: 46, label: "DDR System Songs + Replicant Mix" },
        { id: 47, label: "YUNI (SUMMER)" },
        { id: 48, label: "ALICE (SUMMER)" },
        { id: 49, label: "Reach the Sky, Without You" },
        { id: 50, label: "†渚の小悪魔ラヴリィ～レイディオ†" },
        { id: 51, label: "天空の華" },
        { id: 52, label: "灰庭まよい" },
        { id: 53, label: "ヒネリ" },
        { id: 54, label: "Beluga" },
        { id: 55, label: "Unreality" },
        { id: 56, label: "Come Back to Me (Feel It)" },
        { id: 57, label: "博麗 霊夢" },
        { id: 58, label: "東風谷 早苗" },
        { id: 59, label: "古明地 こいし" },
        { id: 60, label: "フランドール・スカーレット" },
        { id: 61, label: "残像ニ繋ガレタ追憶ノHIDEAWAY" },
        { id: 62, label: "弾幕信仰" },
        { id: 100001, label: "APINA VRAMeS" },
        { id: 100002, label: "GiGO" },
        { id: 100003, label: "GamePanic" },
        { id: 100004, label: "Silk Hat" },
        { id: 100005, label: "TAITO STATION Tradz" },
        { id: 100006, label: "ROUND1" },
        { id: 100007, label: "Leisureland" },
      ],
    },
    {
      id: "customize.3_1",
      name: "Game Background (system)",
      help: "Choose your system background",
      type: "Array",
      options: [
        { id: 1, label: "WORLD (パターン1)" },
        { id: 2, label: "WORLD (パターン2)" },
        { id: 3, label: "WORLD (パターン3)" },
        { id: 4, label: "ヘキサグラム (パターン1)" },
        { id: 5, label: "ヘキサグラム (パターン2)" },
        { id: 6, label: "ヘキサグラム (パターン3)" },
        { id: 7, label: "ヘキサグラム (パターン4)" },
        { id: 8, label: "ヘキサグラム (パターン5)" },
        { id: 9, label: "BPL S2" },
        { id: 10, label: "BPL S4" },
        { id: 11, label: "EMIまみれ (BPL S4)" },
        { id: 12, label: "ちくわまつり2023" },
        { id: 13, label: "ちくわまつり2025" },
        { id: 14, label: "ひなビタ♪＆ここなつ ミニキャラ大集合" },
        { id: 15, label: "ひなビタ♪＆ここなつ スライドショー" },
        { id: 16, label: "ARROW (パターン1)" },
        { id: 17, label: "ARROW (パターン2)" },
        { id: 18, label: "ARROW (パターン3)" },
        { id: 19, label: "ARROW (パターン4)" },
        { id: 20, label: "ARROW (パターン5)" },
        { id: 21, label: "WORLD (パターン4)" },
        { id: 22, label: "ARROW (パターン6)" },
        { id: 23, label: "ヘキサグラム (パターン6)" },
        { id: 24, label: "WORLD (パターン5)" },
        { id: 25, label: "春のコナステ大感謝祭2024" },
        { id: 26, label: "ミニマスコット大集合 (春のコナステ大感謝祭2024)" },
        { id: 27, label: "Character Slideshow (春のコナステ大感謝祭2024)" },
        { id: 28, label: "OCEAN (パターン1)" },
        { id: 29, label: "OCEAN (パターン2)" },
        { id: 30, label: "OCEAN (パターン3)" },
        { id: 31, label: "HYPER DISTORTION (パターン1)" },
        { id: 32, label: "HYPER DISTORTION (パターン2)" },
        { id: 33, label: "HYPER DISTORTION (パターン3)" },
        { id: 34, label: "幻想郷音樂祭2024" },
        { id: 35, label: "古明地 こいし&フランドール・スカーレット" },
      ],
    },
    {
      id: "customize.3_2",
      name: "Game Background (while playing music)",
      help: "Choose your in-game system background",
      type: "Array",
      options: [
        { id: 1, label: "WORLD (パターン1)" },
        { id: 2, label: "WORLD (パターン2)" },
        { id: 3, label: "WORLD (パターン3)" },
        { id: 4, label: "ヘキサグラム (パターン1)" },
        { id: 5, label: "ヘキサグラム (パターン2)" },
        { id: 6, label: "ヘキサグラム (パターン3)" },
        { id: 7, label: "ヘキサグラム (パターン4)" },
        { id: 8, label: "ヘキサグラム (パターン5)" },
        { id: 9, label: "BPL S2" },
        { id: 10, label: "BPL S4" },
        { id: 11, label: "EMIまみれ (BPL S4)" },
        { id: 12, label: "ちくわまつり2023" },
        { id: 13, label: "ちくわまつり2025" },
        { id: 14, label: "ひなビタ♪＆ここなつ ミニキャラ大集合" },
        { id: 15, label: "ひなビタ♪＆ここなつ スライドショー" },
        { id: 16, label: "ARROW (パターン1)" },
        { id: 17, label: "ARROW (パターン2)" },
        { id: 18, label: "ARROW (パターン3)" },
        { id: 19, label: "ARROW (パターン4)" },
        { id: 20, label: "ARROW (パターン5)" },
        { id: 21, label: "WORLD (パターン4)" },
        { id: 22, label: "ARROW (パターン6)" },
        { id: 23, label: "ヘキサグラム (パターン6)" },
        { id: 24, label: "WORLD (パターン5)" },
        { id: 25, label: "春のコナステ大感謝祭2024" },
        { id: 26, label: "ミニマスコット大集合 (春のコナステ大感謝祭2024)" },
        { id: 27, label: "Character Slideshow (春のコナステ大感謝祭2024)" },
        { id: 28, label: "OCEAN (パターン1)" },
        { id: 29, label: "OCEAN (パターン2)" },
        { id: 30, label: "OCEAN (パターン3)" },
        { id: 31, label: "HYPER DISTORTION (パターン1)" },
        { id: 32, label: "HYPER DISTORTION (パターン2)" },
        { id: 33, label: "HYPER DISTORTION (パターン3)" },
        { id: 34, label: "幻想郷音樂祭2024" },
        { id: 35, label: "古明地 こいし&フランドール・スカーレット" },
      ],
    },
    {
      id: "customize.2_1",
      name: "System Character (left side)",
      help: "Choose your system character for the left side",
      type: "Array",
      options: [
        { id: 1, label: "EMI" },
        { id: 2, label: "RAGE" },
        { id: 3, label: "ALICE" },
        { id: 4, label: "BABY-LON" },
        { id: 5, label: "EMI (BPL S4)" },
        { id: 6, label: "RAGE (BPL S4)" },
        { id: 7, label: "山形まり花 (Marika Yamagata)" },
        { id: 8, label: "和泉一舞 (Izumi Ibuki)" },
        { id: 9, label: "春日咲子 (Sakiko Kasuga)" },
        { id: 10, label: "芽兎めう (Meto Meu)" },
        { id: 11, label: "霜月凛 (Rin Shimotsuki)" },
        { id: 12, label: "東雲夏陽 (Shinonome Natsuhi)" },
        { id: 13, label: "東雲心菜 (Shinonome Cocona)" },
        { id: 14, label: "YUNI" },
        { id: 15, label: "AKIRA" },
        { id: 16, label: "天戸紺 (Amado Kon)" },
        { id: 17, label: "小舞桜 (Komai Sakura)" },
        { id: 18, label: "TSUGARU (春のコナステ大感謝祭2024)" },
        { id: 19, label: "GRACE (春のコナステ大感謝祭2024)" },
        { id: 20, label: "RINON (春のコナステ大感謝祭2024)" },
        { id: 21, label: "MIMI (春のコナステ大感謝祭2024)" },
        { id: 22, label: "RIO (春のコナステ大感謝祭2024)" },
        { id: 23, label: "YUNI (SUMMER)" },
        { id: 24, label: "ALICE (SUMMER)" },
        { id: 25, label: "灰庭まよい" },
        { id: 26, label: "ヒネリ" },
        { id: 27, label: "博麗 霊夢" },
        { id: 28, label: "東風谷 早苗" },
        { id: 29, label: "古明地 こいし" },
        { id: 30, label: "フランドール・スカーレット" },
      ],
    },
    {
      id: "customize.2_2",
      name: "System Character (right side)",
      help: "Choose your system character for the right side",
      type: "Array",
      options: [
        { id: 1, label: "EMI" },
        { id: 2, label: "RAGE" },
        { id: 3, label: "ALICE" },
        { id: 4, label: "BABY-LON" },
        { id: 5, label: "EMI (BPL S4)" },
        { id: 6, label: "RAGE (BPL S4)" },
        { id: 7, label: "山形まり花 (Marika Yamagata)" },
        { id: 8, label: "和泉一舞 (Izumi Ibuki)" },
        { id: 9, label: "春日咲子 (Sakiko Kasuga)" },
        { id: 10, label: "芽兎めう (Meto Meu)" },
        { id: 11, label: "霜月凛 (Rin Shimotsuki)" },
        { id: 12, label: "東雲夏陽 (Shinonome Natsuhi)" },
        { id: 13, label: "東雲心菜 (Shinonome Cocona)" },
        { id: 14, label: "YUNI" },
        { id: 15, label: "AKIRA" },
        { id: 16, label: "天戸紺 (Amado Kon)" },
        { id: 17, label: "小舞桜 (Komai Sakura)" },
        { id: 18, label: "TSUGARU (春のコナステ大感謝祭2024)" },
        { id: 19, label: "GRACE (春のコナステ大感謝祭2024)" },
        { id: 20, label: "RINON (春のコナステ大感謝祭2024)" },
        { id: 21, label: "MIMI (春のコナステ大感謝祭2024)" },
        { id: 22, label: "RIO (春のコナステ大感謝祭2024)" },
        { id: 23, label: "YUNI (SUMMER)" },
        { id: 24, label: "ALICE (SUMMER)" },
        { id: 25, label: "灰庭まよい" },
        { id: 26, label: "ヒネリ" },
        { id: 26, label: "ヒネリ" },
        { id: 27, label: "博麗 霊夢" },
        { id: 28, label: "東風谷 早苗" },
        { id: 29, label: "古明地 こいし" },
        { id: 30, label: "フランドール・スカーレット" },
      ],
    },
    {
      id: "customize.6_1",
      name: "Lane Cover (SINGLE)",
      help: "Choose your lane cover for single play",
      type: "Array",
      options: [
        { id: 1, label: "WORLD" },
        { id: 2, label: "EMI" },
        { id: 3, label: "RAGE" },
        { id: 4, label: "ROCKET" },
        { id: 5, label: "ALICE" },
        { id: 6, label: "BABY-LON" },
        { id: 7, label: "みゅ、みゅ、Müllる" },
        { id: 8, label: "Astrogazer" },
        { id: 9, label: "Don't Stop The HYPERCORE" },
        { id: 10, label: "BPL S2" },
        { id: 11, label: "BPL S4" },
        { id: 12, label: "EMI (BPL S4)" },
        { id: 13, label: "RAGE (BPL S4)" },
        { id: 14, label: "ひなビタ♪ Chocolate Smile Girls!!" },
        { id: 15, label: "ヒカリユリイカ" },
        { id: 16, label: "ここなつ シンクロノーツ" },
        { id: 17, label: "革命パッショネイト" },
        { id: 18, label: "ひなビタ♪ SWEET SMILE PARADE" },
        { id: 19, label: "ホーンテッド★メイドランチ (一舞＆咲子ver.)" },
        { id: 20, label: "滅亡天使 † にこきゅっぴん" },
        { id: 21, label: "YUNI" },
        { id: 22, label: "AKIRA" },
        { id: 23, label: "Destination" },
        { id: 24, label: "HyperTwist" },
        { id: 25, label: "Cosy Catastrophe" },
        { id: 26, label: "New York EVOLVED" },
        { id: 27, label: "bag (EXPERT譜面 x0.25 WAVE)" },
        { id: 28, label: "天戸紺 (Amado Kon)" },
        { id: 29, label: "小舞桜 (Komai Sakura)" },
        { id: 30, label: "Deep tenDon Reflex" },
        { id: 31, label: "ROCK THE PARTY" },
        { id: 32, label: "エンドルフィン" },
        { id: 33, label: "†渚の小悪魔ラヴリィ～レイディオ† (CHALLENGE譜面)" },
        { id: 34, label: "TSUGARU (春のコナステ大感謝祭2024)" },
        { id: 35, label: "GRACE (春のコナステ大感謝祭2024)" },
        { id: 36, label: "RINON (春のコナステ大感謝祭2024)" },
        { id: 37, label: "MIMI (春のコナステ大感謝祭2024)" },
        { id: 38, label: "RIO (春のコナステ大感謝祭2024)" },
        { id: 39, label: "DDR System Songs + Replicant Mix" },
        { id: 40, label: "YUNI (SUMMER)" },
        { id: 41, label: "ALICE (SUMMER)" },
        { id: 42, label: "Reach the Sky, Without You" },
        { id: 43, label: "†渚の小悪魔ラヴリィ～レイディオ†" },
        { id: 44, label: "天空の華" },
        { id: 45, label: "take me higher" },
        { id: 46, label: "灰庭まよい" },
        { id: 47, label: "ヒネリ" },
        { id: 48, label: "Beluga" },
        { id: 49, label: "Unreality" },
        { id: 50, label: "Come Back to Me (Feel It)" },
        { id: 51, label: "HYPER DRILL" },
        { id: 52, label: "博麗 霊夢" },
        { id: 53, label: "東風谷 早苗" },
        { id: 54, label: "古明地 こいし" },
        { id: 55, label: "フランドール・スカーレット" },
        { id: 56, label: "残像ニ繋ガレタ追憶ノHIDEAWAY" },
        { id: 57, label: "弾幕信仰" },
      ],
    },
    {
      id: "customize.7_1",
      name: "Lane Cover (DOUBLE)",
      help: "Choose your lane cover for double play",
      type: "Array",
      options: [
        { id: 1, label: "WORLD" },
        { id: 2, label: "EMI" },
        { id: 3, label: "RAGE" },
        { id: 4, label: "EMI&RAGE" },
        { id: 5, label: "ROCKET" },
        { id: 6, label: "ALICE" },
        { id: 7, label: "BABY-LON" },
        { id: 8, label: "ALICE&EMI" },
        { id: 9, label: "みゅ、みゅ、Müllる" },
        { id: 10, label: "Astrogazer" },
        { id: 11, label: "Don't Stop The HYPERCORE" },
        { id: 12, label: "BPL S2" },
        { id: 13, label: "BPL S4" },
        { id: 14, label: "EMI & RAGE (BPL S4 パターン1)" },
        { id: 15, label: "EMI & RAGE (BPL S4 パターン2)" },
        { id: 16, label: "EMIまみれ (BPL S4)" },
        { id: 17, label: "ナナイロライト" },
        { id: 18, label: "じもとっこスイーツ♪" },
        { id: 19, label: "ハレ トキドキ メランコリック" },
        { id: 20, label: "ひなビタ♪ お花見ライブ" },
        { id: 21, label: "ひなビタ♪ 肝試し" },
        { id: 22, label: "滅びに至るエランプシス" },
        { id: 23, label: "カタルシスの月" },
        { id: 24, label: "YUNI" },
        { id: 25, label: "AKIRA" },
        { id: 26, label: "Destination" },
        { id: 27, label: "HyperTwist" },
        { id: 28, label: "Cosy Catastrophe" },
        { id: 29, label: "New York EVOLVED" },
        { id: 30, label: "bag (EXPERT譜面 x0.25 WAVE)" },
        { id: 31, label: "YUNI & AKIRA" },
        { id: 32, label: "ALICE & YUNI" },
        { id: 33, label: "天戸紺 (Amado Kon)" },
        { id: 34, label: "小舞桜 (Komai Sakura)" },
        { id: 35, label: "天戸紺 & 小舞桜 (Amado Kon & Komai Sakura)" },
        { id: 36, label: "Deep tenDon Reflex" },
        { id: 37, label: "ROCK THE PARTY" },
        { id: 38, label: "エンドルフィン" },
        { id: 39, label: "†渚の小悪魔ラヴリィ～レイディオ† (CHALLENGE譜面)" },
        { id: 40, label: "TSUGARU (春のコナステ大感謝祭2024)" },
        { id: 41, label: "GRACE (春のコナステ大感謝祭2024)" },
        { id: 42, label: "RINON (春のコナステ大感謝祭2024)" },
        { id: 43, label: "MIMI (春のコナステ大感謝祭2024)" },
        { id: 44, label: "RIO (春のコナステ大感謝祭2024)" },
        { id: 45, label: "All Characters Assembly (春のコナステ大感謝祭2024)" },
        { id: 46, label: "DDR System Songs + Replicant Mix" },
        { id: 47, label: "YUNI (SUMMER)" },
        { id: 48, label: "ALICE (SUMMER)" },
        { id: 49, label: "YUNI (SUMMER) & ALICE (SUMMER)" },
        { id: 50, label: "Reach the Sky, Without You" },
        { id: 51, label: "†渚の小悪魔ラヴリィ～レイディオ†" },
        { id: 52, label: "天空の華" },
        { id: 53, label: "take me higher" },
        { id: 54, label: "灰庭まよい" },
        { id: 55, label: "ヒネリ" },
        { id: 56, label: "灰庭まよい & ヒネリ" },
        { id: 57, label: "Beluga" },
        { id: 58, label: "Unreality" },
        { id: 59, label: "Come Back to Me (Feel It)" },
        { id: 60, label: "HYPER DRILL" },
        { id: 61, label: "博麗 霊夢" },
        { id: 62, label: "東風谷 早苗" },
        { id: 63, label: "古明地 こいし" },
        { id: 64, label: "フランドール・スカーレット" },
        { id: 65, label: "残像ニ繋ガレタ追憶ノHIDEAWAY" },
        { id: 66, label: "弾幕信仰" },
        { id: 67, label: "博麗 霊夢&東風谷 早苗" },
        { id: 68, label: "古明地 こいし&フランドール・スカーレット" },
      ],
    },
    {
      id: "customize.4_1",
      name: "Lane Background (SINGLE)",
      help: "Choose your lane background for single play",
      type: "Array",
      options: [
        { id: 1, label: "EMI" },
        { id: 2, label: "RAGE" },
        { id: 3, label: "ROCKET" },
        { id: 4, label: "ALICE" },
        { id: 5, label: "BABY-LON" },
        { id: 6, label: "GRID" },
        { id: 7, label: "BPL S2" },
        { id: 8, label: "BPL S4" },
        { id: 9, label: "EMI (BPL S4)" },
        { id: 10, label: "RAGE (BPL S4)" },
        { id: 11, label: "山形まり花 (Marika Yamagata)" },
        { id: 12, label: "和泉一舞 (Izumi Ibuki)" },
        { id: 13, label: "春日咲子 (Sakiko Kasuga)" },
        { id: 14, label: "芽兎めう (Meto Meu)" },
        { id: 15, label: "霜月凛 (Rin Shimotsuki)" },
        { id: 16, label: "東雲夏陽 (Shinonome Natsuhi)" },
        { id: 17, label: "東雲心菜 (Shinonome Cocona)" },
        { id: 18, label: "YUNI" },
        { id: 19, label: "AKIRA" },
        { id: 20, label: "HONEYCOMB" },
        { id: 21, label: "bag (EXPERT譜面 x0.25 WAVE)" },
        { id: 22, label: "天戸紺 (Amado Kon)" },
        { id: 23, label: "小舞桜 (Komai Sakura)" },
        { id: 24, label: "†渚の小悪魔ラヴリィ～レイディオ† (CHALLENGE譜面)" },
        { id: 25, label: "TSUGARU (春のコナステ大感謝祭2024)" },
        { id: 26, label: "GRACE (春のコナステ大感謝祭2024)" },
        { id: 27, label: "RINON (春のコナステ大感謝祭2024)" },
        { id: 28, label: "MIMI (春のコナステ大感謝祭2024)" },
        { id: 29, label: "RIO (春のコナステ大感謝祭2024)" },
        { id: 30, label: "TRIANGLE" },
        { id: 31, label: "YUNI (SUMMER)" },
        { id: 32, label: "ALICE (SUMMER)" },
        { id: 33, label: "SUNFLOWER" },
        { id: 34, label: "灰庭まよい" },
        { id: 35, label: "ヒネリ" },
        { id: 36, label: "HYPER DRILL" },
        { id: 37, label: "博麗 霊夢" },
        { id: 38, label: "東風谷 早苗" },
        { id: 39, label: "古明地 こいし" },
        { id: 40, label: "フランドール・スカーレット" },
        { id: 41, label: "残像ニ繋ガレタ追憶ノHIDEAWAY" },
        { id: 42, label: "弾幕信仰" },
      ],
    },
    {
      id: "customize.5_1",
      name: "Lane Background (DOUBLE)",
      help: "Choose your lane background for double play",
      type: "Array",
      options: [
        { id: 1, label: "EMI&RAGE" },
        { id: 2, label: "EMI" },
        { id: 3, label: "RAGE" },
        { id: 4, label: "ROCKET" },
        { id: 5, label: "ALICE" },
        { id: 6, label: "BABY-LON" },
        { id: 7, label: "ALICE&EMI" },
        { id: 8, label: "GRID" },
        { id: 9, label: "BPL S2" },
        { id: 10, label: "BPL S4" },
        { id: 11, label: "EMI (BPL S4)" },
        { id: 12, label: "RAGE (BPL S4)" },
        { id: 13, label: "EMI & RAGE (BPL S4)" },
        { id: 14, label: "ナナイロライト" },
        { id: 15, label: "じもとっこスイーツ♪" },
        { id: 16, label: "ハレ トキドキ メランコリック" },
        { id: 17, label: "ひなビタ♪ お花見ライブ" },
        { id: 18, label: "ひなビタ♪ 肝試し" },
        { id: 19, label: "滅びに至るエランプシス" },
        { id: 20, label: "カタルシスの月" },
        { id: 21, label: "YUNI" },
        { id: 22, label: "AKIRA" },
        { id: 23, label: "HONEYCOMB" },
        { id: 24, label: "bag (EXPERT譜面 x0.25 WAVE)" },
        { id: 25, label: "YUNI & AKIRA" },
        { id: 26, label: "ALICE & YUNI" },
        { id: 27, label: "天戸紺 (Amado Kon)" },
        { id: 28, label: "小舞桜 (Komai Sakura)" },
        { id: 29, label: "天戸紺 & 小舞桜 (Amado Kon & Komai Sakura)" },
        { id: 30, label: "†渚の小悪魔ラヴリィ～レイディオ† (CHALLENGE譜面)" },
        { id: 31, label: "TSUGARU (春のコナステ大感謝祭2024)" },
        { id: 32, label: "GRACE (春のコナステ大感謝祭2024)" },
        { id: 33, label: "RINON (春のコナステ大感謝祭2024)" },
        { id: 34, label: "MIMI (春のコナステ大感謝祭2024)" },
        { id: 35, label: "RIO (春のコナステ大感謝祭2024)" },
        { id: 36, label: "All Characters Assembly (春のコナステ大感謝祭2024)" },
        { id: 37, label: "TRIANGLE" },
        { id: 38, label: "YUNI (SUMMER)" },
        { id: 39, label: "ALICE (SUMMER)" },
        { id: 40, label: "YUNI (SUMMER) & ALICE (SUMMER)" },
        { id: 41, label: "SUNFLOWER" },
        { id: 42, label: "灰庭まよい" },
        { id: 43, label: "ヒネリ" },
        { id: 44, label: "灰庭まよい & ヒネリ" },
        { id: 45, label: "HYPER DRILL" },
        { id: 46, label: "博麗 霊夢" },
        { id: 47, label: "東風谷 早苗" },
        { id: 48, label: "古明地 こいし" },
        { id: 49, label: "フランドール・スカーレット" },
        { id: 50, label: "残像ニ繋ガレタ追憶ノHIDEAWAY" },
        { id: 51, label: "弾幕信仰" },
        { id: 52, label: "博麗 霊夢 & 東風谷 早苗" },
        { id: 53, label: "古明地 こいし&フランドール・スカーレット" },
      ],
    },
    {
      id: "customize.8_1",
      name: "Background Video",
      help: "Choose your background video setting",
      type: "Array",
      options: [
        { id: 0, label: "Fullscreen Video" },
        { id: 1, label: "Small Video" },
        { id: 2, label: "Off" },
      ],
    },
  ],
};
