export const DDROptions = {
  16: [
    {
      id: "early_late",
      name: "Fast/Slow Display",
      help: "Enable or disable displaying of Fast/Slow",
      type: "Boolean",
    },
    {
      id: "combo",
      name: "Combo Position",
      help: "Change order of the combo and notes",
      type: "Boolean",
    },
    {
      id: "weight",
      name: "Weight (kg)",
      help: "Set your weight for in-game workout mode",
      type: "Number",
    },
    {
      id: "character",
      name: "Character",
      help: "Select your character",
      type: "Array",
      options: [
        { id: 0, label: "All Character Random" },
        { id: 1, label: "Male Random" },
        { id: 2, label: "Female Random" },
        { id: 3, label: "Yuni" },
        { id: 4, label: "Rage" },
        { id: 5, label: "Afro" },
        { id: 6, label: "Jenny" },
        { id: 7, label: "Emi" },
        { id: 8, label: "Baby-Lon" },
        { id: 9, label: "Gus" },
        { id: 10, label: "Ruby" },
        { id: 11, label: "Alice" },
        { id: 12, label: "Julio" },
        { id: 13, label: "Bonnie" },
        { id: 14, label: "Zero" },
        { id: 15, label: "Rinon" },
        { id: 16, label: "Ryusei Emi" },
        { id: 17, label: "Ryusei Alice" },
        { id: 18, label: "Ryusei Rinon" },
        { id: 19, label: "KAC Yuni" },
        { id: 20, label: "Dark Rinon" },
        { id: 21, label: "Victory Concent" },
        { id: 22, label: "Geisha Zukin" },
        { id: 23, label: "Green Pix" },
        { id: 24, label: "Ace Emi" },
        { id: 25, label: "X2 Yuni" },
        { id: 26, label: "X2 Rage" },
        { id: 27, label: "X2 Afro" },
        { id: 28, label: "X2 Jenny" },
      ],
    },
    {
      id: "arrowskin",
      name: "Arrow Skin",
      help: "Set your arrow skin",
      type: "Array",
      options: [
        { id: 0, label: "Normal" },
        { id: 1, label: "New" },
        { id: 2, label: "Classic" },
        { id: 3, label: "Cyber" },
        { id: 4, label: "Medium" },
        { id: 5, label: "Small" },
        { id: 6, label: "Dot" },
      ],
    },
    {
      id: "guidelines",
      name: "Guidelines",
      help: "Set the guideline style",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Border" },
        { id: 2, label: "Center" },
      ],
    },
    {
      id: "filter",
      name: "Filter",
      help: "Set the filter intensity",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Dark" },
        { id: 2, label: "Darker" },
        { id: 3, label: "Darkest" },
      ],
    },
  ],
  17: [
    {
      id: "early_late",
      name: "Fast/Slow Display",
      help: "Enable or disable displaying of Fast/Slow",
      type: "Boolean",
    },
    {
      id: "combo",
      name: "Combo Position",
      help: "Change order of the combo and notes",
      type: "Boolean",
    },
    {
      id: "weight",
      name: "Weight (kg)",
      help: "Set your weight for in-game workout mode",
      type: "Number",
    },
    {
      id: "character",
      name: "Character",
      help: "Select your character",
      type: "Array",
      options: [
        { id: 0, label: "All Character Random" },
        { id: 1, label: "Male Random" },
        { id: 2, label: "Female Random" },
        { id: 3, label: "Yuni" },
        { id: 4, label: "Rage" },
        { id: 5, label: "Afro" },
        { id: 6, label: "Jenny" },
        { id: 7, label: "Emi" },
        { id: 8, label: "Baby-Lon" },
        { id: 9, label: "Gus" },
        { id: 10, label: "Ruby" },
        { id: 11, label: "Alice" },
        { id: 12, label: "Julio" },
        { id: 13, label: "Bonnie" },
        { id: 14, label: "Zero" },
        { id: 15, label: "Rinon" },
      ],
    },
    {
      id: "arrowskin",
      name: "Arrow Skin",
      help: "Set your arrow skin",
      type: "Array",
      options: [
        { id: 0, label: "Normal" },
        { id: 1, label: "New" },
        { id: 2, label: "Classic" },
        { id: 3, label: "Cyber" },
        { id: 4, label: "Medium" },
        { id: 5, label: "Small" },
        { id: 6, label: "Dot" },
      ],
    },
    {
      id: "guidelines",
      name: "Guidelines",
      help: "Set the guideline style",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Border" },
        { id: 2, label: "Center" },
      ],
    },
    {
      id: "filter",
      name: "Filter",
      help: "Set the filter intensity",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Dark" },
        { id: 2, label: "Darker" },
        { id: 3, label: "Darkest" },
      ],
    },
  ],
  18: [
    {
      id: "early_late",
      name: "Fast/Slow Display",
      help: "Enable or disable displaying of Fast/Slow",
      type: "Boolean",
    },
    {
      id: "combo",
      name: "Combo Position",
      help: "Change order of the combo and notes",
      type: "Boolean",
    },
    {
      id: "weight",
      name: "Weight (kg)",
      help: "Set your weight for in-game workout mode",
      type: "Number",
    },
    {
      id: "character",
      name: "Character",
      help: "Select your character",
      type: "Array",
      options: [
        { id: 0, label: "All Character Random" },
        { id: 1, label: "Male Random" },
        { id: 2, label: "Female Random" },
        { id: 3, label: "Yuni" },
        { id: 4, label: "Rage" },
        { id: 5, label: "Afro" },
        { id: 6, label: "Jenny" },
        { id: 7, label: "Emi" },
        { id: 8, label: "Baby-Lon" },
        { id: 9, label: "Gus" },
        { id: 10, label: "Ruby" },
        { id: 11, label: "Alice" },
        { id: 12, label: "Julio" },
        { id: 13, label: "Bonnie" },
        { id: 14, label: "Zero" },
        { id: 15, label: "Rinon" },
      ],
    },
    {
      id: "arrowskin",
      name: "Arrow Skin",
      help: "Set your arrow skin",
      type: "Array",
      options: [
        { id: 0, label: "Normal" },
        { id: 1, label: "New" },
        { id: 2, label: "Classic" },
        { id: 3, label: "Cyber" },
        { id: 4, label: "Medium" },
        { id: 5, label: "Small" },
        { id: 6, label: "Dot" },
      ],
    },
    {
      id: "guidelines",
      name: "Guidelines",
      help: "Set the guideline style",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Border" },
        { id: 2, label: "Center" },
      ],
    },
    {
      id: "filter",
      name: "Filter",
      help: "Set the filter intensity",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Dark" },
        { id: 2, label: "Darker" },
        { id: 3, label: "Darkest" },
      ],
    },
  ],
  19: [
    {
      id: "early_late",
      name: "Fast/Slow Display",
      help: "Enable or disable displaying of Fast/Slow",
      type: "Boolean",
    },
    {
      id: "combo",
      name: "Combo Position",
      help: "Change order of the combo and notes",
      type: "Boolean",
    },
    {
      id: "weight",
      name: "Weight (kg)",
      help: "Set your weight for in-game workout mode",
      type: "Number",
    },
    {
      id: "character",
      name: "Character",
      help: "Select your character",
      type: "Array",
      options: [
        { id: 0, label: "All Character Random" },
        { id: 1, label: "Male Random" },
        { id: 2, label: "Female Random" },
        { id: 3, label: "Yuni" },
        { id: 4, label: "Rage" },
        { id: 5, label: "Afro" },
        { id: 6, label: "Jenny" },
        { id: 7, label: "Emi" },
        { id: 8, label: "Baby-Lon" },
        { id: 9, label: "Gus" },
        { id: 10, label: "Ruby" },
        { id: 11, label: "Alice" },
        { id: 12, label: "Julio" },
        { id: 13, label: "Bonnie" },
        { id: 14, label: "Zero" },
        { id: 15, label: "Rinon" },
      ],
    },
    {
      id: "arrowskin",
      name: "Arrow Skin",
      help: "Set your arrow skin",
      type: "Array",
      options: [
        { id: 0, label: "Normal" },
        { id: 1, label: "New" },
        { id: 2, label: "Classic" },
        { id: 3, label: "Cyber" },
        { id: 4, label: "Medium" },
        { id: 5, label: "Small" },
        { id: 6, label: "Dot" },
      ],
    },
    {
      id: "guidelines",
      name: "Guidelines",
      help: "Set the guideline style",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Border" },
        { id: 2, label: "Center" },
      ],
    },
    {
      id: "opt_appearance",
      name: "Appearance Option",
      help: "Set your appearance option",
      type: "Array",
      options: [
        { id: 0, label: "Normal" },
        { id: 1, label: "Hidden" },
        { id: 2, label: "Sudden" },
        { id: 3, label: "Hidden +" },
        { id: 4, label: "Sudden +" },
        { id: 5, label: "Hidden & Sudden +" },
        { id: 6, label: "Stealth" },
      ],
    },
    {
      id: "filter",
      name: "Filter",
      help: "Set the filter intensity",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Dark" },
        { id: 2, label: "Darker" },
        { id: 3, label: "Darkest" },
      ],
    },
    {
      id: "bpl_flag",
      name: "BPL Flag",
      help: "Choose your BPL flag",
      type: "Array",
      options: [
        { id: 0, label: "Off" },
        { id: 1, label: "Apina Vrames" },
        { id: 2, label: "Gigo" },
        { id: 3, label: "Game Panic" },
        { id: 4, label: "Silk Hat" },
        { id: 5, label: "SUPER NOVA Tohoku" },
        { id: 6, label: "TradZ" },
        { id: 7, label: "ROUND 1" },
        { id: 8, label: "Leisure Land" },
      ],
    },
  ],
};
