export const IIDXOptions = {
  20: [
    {
      id: "global_shop_ranking",
      name: "Global Shop Ranking",
      help: "Return network-wide ranking instead of shop ranking on results screen.",
      type: "Boolean",
    },
    {
      id: "cafe_enable",
      name: "Café de Tran",
      help: "Enable the Café de Tran event.",
      type: "Boolean",
    },
    {
      id: "gakuen_enable",
      name: "Shiritsu BEMANI gakuen (私立BEMANI学園)",
      help: "Enable the Shiritsu BEMANI gakuen (私立BEMANI学園) event.",
      type: "Boolean",
    },
    {
      id: "uchuu_enable",
      name: "Q-pro, Mimi, Nyami & Pastel-kun no minna de uchuu sensou!!",
      help: "Enable the Q-pro, Mimi, Nyami & Pastel-kun no minna de uchuu sensou!! event.",
      type: "Boolean",
    },
    {
      id: "limit_phase",
      name: "LIMIT BURST PHASE",
      help: "Sets the LIMIT BURST Phase.",
      type: "Array",
      options: [
        { id: 0, label: "LIMIT BURST OFF" },
        { id: 1, label: "Phase 1" },
        { id: 2, label: "Phase 2" },
        { id: 3, label: "Phase 3" },
        { id: 4, label: "Phase 4" },
      ],
    },
    {
      id: "event_phase",
      name: "Current Active Event",
      help: "Sets the machine Event Phase.",
      type: "Array",
      options: [
        { id: 0, label: "No Boss Event" },
        { id: 1, label: "LEGEND CROSS (RED)" },
        { id: 2, label: "Ω-ATTACK (BLUE)" },
      ],
    },
    {
      id: "red_phase",
      name: "Current RED Phase",
      help: "Sets the machine RED Phase.",
      type: "Array",
      options: [
        { id: 0, label: "Phase 1" },
        { id: 1, label: "Phase 2" },
        { id: 2, label: "Phase 3" },
      ],
    },
    {
      id: "yellow_phase",
      name: "Current YELLOW Phase",
      help: "Sets the machine YELLOW Phase.",
      type: "Array",
      options: [
        { id: 0, label: "Phase 1" },
        { id: 1, label: "Phase 2" },
        { id: 2, label: "Phase 3" },
      ],
    },
  ],
  21: [
    {
      id: "global_shop_ranking",
      name: "Global Shop Ranking",
      help: "Return network-wide ranking instead of shop ranking on results screen.",
      type: "Boolean",
    },
    {
      id: "event_phase",
      name: "Qprogue",
      help: "Sets the Qprogue Map.",
      type: "Array",
      options: [
        { id: 0, label: "Disable Qpronicle Chord" },
        { id: 1, label: "Map 1 - Departure" },
        { id: 2, label: "Map 2 - The Blue Earth (1)" },
        { id: 3, label: "Map 3 - The Blue Earth (2)" },
        { id: 4, label: "MAP DX-1" },
        { id: 5, label: "MAP DX-2" },
        { id: 6, label: "MAP DX-3" },
        { id: 7, label: "MAP DX-4" },
        { id: 8, label: "MAP DX-5" },
        { id: 9, label: "MAP DX-6" },
        { id: 10, label: "MAP DX-7" },
      ],
    },
  ],
  22: [
    {
      id: "global_shop_ranking",
      name: "Global Shop Ranking",
      help: "Return network-wide ranking instead of shop ranking on results screen.",
      type: "Boolean",
    },
    {
      id: "ccxbm_enable",
      name: "CocaColaXBEMANI",
      help: "Enables the CocaColaXBEMANI event. Enables all of the custom frames on older data.",
      type: "Boolean",
    },
    {
      id: "cycle_config",
      name: "Present/Future Cycle",
      help: "Override server defaults for present/future cycle.",
      type: "Array",
      options: [
        { id: 0, label: "Standard Rotation" },
        { id: 1, label: "Swap Present/Future" },
        { id: 2, label: "Force Present" },
        { id: 3, label: "Force Future" },
      ],
    },
    {
      id: "event_phase",
      name: "Event Phase",
      help: "Sets the boss event phase.",
      type: "Array",
      options: [
        { id: 0, label: "No Boss Event" },
        { id: 1, label: "Chrono Seeker" },
        { id: 2, label: "Qpronicle Chord" },
        { id: 3, label: "-Densetsu renkin- PENDUAL TALISMAN" },
      ],
    },
  ],
  23: [
    {
      id: "global_shop_ranking",
      name: "Global Shop Ranking",
      help: "Return network-wide ranking instead of shop ranking on results screen.",
      type: "Boolean",
    },
    {
      id: "omnimix_events_enabled",
      name: "Events In Omnimix",
      help: "Allow events to be enabled at all for Omnimix.",
      type: "Boolean",
    },
    {
      id: "event_phase",
      name: "Event Phase",
      help: "Sets the Boss Event Phase.",
      type: "Array",
      options: [
        { id: 0, label: "No Boss Event" },
        { id: 1, label: "Tokotoko Line" },
        { id: 2, label: "Mystery Line Phase 1" },
        { id: 3, label: "Mystery Line Phase 2" },
        { id: 4, label: "Mystery Line Phase 3" },
      ],
    },
  ],
  24: [
    {
      id: "global_shop_ranking",
      name: "Global Shop Ranking",
      help: "Return network-wide ranking instead of shop ranking on results screen.",
      type: "Boolean",
    },
    {
      id: "omnimix_events_enabled",
      name: "Events In Omnimix",
      help: "Allow events to be enabled at all for Omnimix.",
      type: "Boolean",
    },
    {
      id: "event_phase",
      name: "Event Phase",
      help: "Sets the Boss Event Phase.",
      type: "Array",
      options: [
        { id: 0, label: "No Boss Event" },
        { id: 1, label: "Koujyo SINOBUZ Den Phase 1" },
        { id: 2, label: "Koujyo SINOBUZ Den Phase 2" },
        { id: 3, label: "Koujyo SINOBUZ Den Phase 3" },
        { id: 4, label: "Ninnin Shichikenden" },
      ],
    },
  ],
  25: [
    {
      id: "global_shop_ranking",
      name: "Global Shop Ranking",
      help: "Return network-wide ranking instead of shop ranking on results screen.",
      type: "Boolean",
    },
    {
      id: "omnimix_events_enabled",
      name: "Events In Omnimix",
      help: "Allow events to be enabled at all for Omnimix.",
      type: "Boolean",
    },
    {
      id: "event_phase",
      name: "Event Phase",
      help: "Sets the Boss Event Phase.",
      type: "Array",
      options: [
        { id: 0, label: "No Boss Event" },
        { id: 1, label: "Gekisou! Cannon racer Continent 1" },
        { id: 2, label: "Gekisou! Cannon racer Continent 2" },
        { id: 3, label: "Gekisou! Cannon racer Continent 3" },
        { id: 4, label: "Gekisou! Cannon racer Continent 4" },
      ],
    },
  ],
  26: [
    {
      id: "global_shop_ranking",
      name: "Global Shop Ranking",
      help: "Return network-wide ranking instead of shop ranking on results screen.",
      type: "Boolean",
    },
    {
      id: "omnimix_events_enabled",
      name: "Events In Omnimix",
      help: "Allow events to be enabled at all for Omnimix.",
      type: "Boolean",
    },
    {
      id: "event_phase",
      name: "Event Phase",
      help: "Sets the Boss Event Phase.",
      type: "Array",
      options: [
        { id: 0, label: "No Boss Event" },
        { id: 1, label: "蜃気楼の図書館(The Bibliotheca of Mirage) Phase 1" },
        { id: 2, label: "蜃気楼の図書館(The Bibliotheca of Mirage) Phase 2" },
        { id: 3, label: "蜃気楼の図書館(The Bibliotheca of Mirage) Phase 3" },
        { id: 4, label: "蜃気楼の図書館(The Bibliotheca of Mirage) Phase 4" },
        { id: 5, label: "DELABITY LABORATORY" },
      ],
    },
  ],
  27: [
    {
      id: "global_shop_ranking",
      name: "Global Shop Ranking",
      help: "Return network-wide ranking instead of shop ranking on results screen.",
      type: "Boolean",
    },
  ],
  28: [
    {
      id: "global_shop_ranking",
      name: "Global Shop Ranking",
      help: "Return network-wide ranking instead of shop ranking on results screen.",
      type: "Boolean",
    },
    {
      id: "omnimix_events_enabled",
      name: "Events In Omnimix",
      help: "Allow events to be enabled at all for Omnimix.",
      type: "Boolean",
    },
    {
      id: "event_phase",
      name: "Event Phase",
      help: "Sets the Boss Event Phase.",
      type: "Array",
      options: [
        { id: 0, label: "No Boss Event" },
        { id: 1, label: "召しませ!BISTROVER Asia" },
        { id: 2, label: "召しませ!BISTROVER Europe" },
        { id: 3, label: "召しませ!BISTROVER Northern land" },
        { id: 4, label: "召しませ!BISTROVER North America" },
        { id: 5, label: "召しませ!BISTROVER FINAL" },
      ],
    },
  ],
  29: [
    {
      id: "global_shop_ranking",
      name: "Global Shop Ranking",
      help: "Return network-wide ranking instead of shop ranking on results screen.",
      type: "Boolean",
    },
    {
      id: "omnimix_events_enabled",
      name: "Events In Omnimix",
      help: "Allow events to be enabled at all for Omnimix.",
      type: "Boolean",
    },
    {
      id: "system_season_voice",
      name: "System Season Voice",
      help: "Enable different season voice in Game",
      type: "Array",
      options: [
        { id: 0, label: "Random" },
        { id: 1, label: "Winter" },
        { id: 2, label: "Spring" },
        { id: 3, label: "Summer" },
        { id: 4, label: "Autumn" },
      ],
    },
    {
      id: "event_phase",
      name: "CastHour SPACE",
      help: "Sets the CastHour SPACE Phase.",
      type: "Array",
      options: [
        { id: 0, label: "No Boss Event" },
        { id: 1, label: "PLATFORM 1 Cyber House" },
        { id: 2, label: "PLATFORM 2 Twinkroom" },
        { id: 3, label: "PLATFORM 3 Cinema IIDX" },
        { id: 4, label: "PLATFORM 4 Beat Showcase" },
        { id: 5, label: "PLATFORM 5 FUTURE SCOPE" },
        { id: 6, label: "PLATFORM X Hideout" },
        { id: 7, label: "PLATFORM X2 Hideout II" },
      ],
    },
  ],
  30: [
    {
      id: "global_shop_ranking",
      name: "Global Shop Ranking",
      help: "Return network-wide ranking instead of shop ranking on results screen.",
      type: "Boolean",
    },
    {
      id: "omnimix_events_enabled",
      name: "Events In Omnimix",
      help: "Allow events to be enabled at all for Omnimix.",
      type: "Boolean",
    },
    {
      id: "system_season_voice",
      name: "System Season Voice",
      help: "Enable different season voice in Game",
      type: "Array",
      options: [
        { id: 0, label: "Random" },
        { id: 1, label: "Winter" },
        { id: 2, label: "Spring" },
        { id: 3, label: "Summer" },
        { id: 4, label: "Autumn" },
      ],
    },
    {
      id: "event_phase",
      name: "RESIDENT PARTY",
      help: "Sets the RESIDENT PARTY Phase.",
      type: "Array",
      options: [
        { id: 0, label: "No Boss Event" },
        { id: 1, label: "RESIDENT OPENING PARTY" },
        { id: 2, label: "IIDX NEW YEAR PARTY" },
        { id: 3, label: "SPRING MUSIC PARTY" },
        { id: 4, label: "IIDX SUMMER PARTY" },
        { id: 5, label: "AUTUMN MUSIC PARTY" },
      ],
    },
  ],
  31: [
    {
      id: "global_shop_ranking",
      name: "Global Shop Ranking",
      help: "Return network-wide ranking instead of shop ranking on results screen.",
      type: "Boolean",
    },
    {
      id: "event_phase",
      name: "Game Event Phase",
      help: "Enable different boss events",
      type: "Array",
      options: [
        { id: 0, label: "No Event" },
        { id: 1, label: "MY POLIS DESIGNER (MAP 1)" },
        { id: 2, label: "MY POLIS DESIGNER (MAP 2)" },
        { id: 3, label: "MY POLIS DESIGNER (MAP 3)" },
        { id: 4, label: "MY POLIS DESIGNER (MAP FINAL)" },
        { id: 5, label: "EPOLIS RESTORATION (SYSTEM A)" },
        { id: 6, label: "EPOLIS RESTORATION (SYSTEM B)" },
        { id: 7, label: "EPOLIS RESTORATION (SYSTEM C)" },
        { id: 8, label: "EPOLIS RESTORATION (SYSTEM D + X)" },
      ],
    },
    {
      id: "system_season_voice",
      name: "System Season Voice",
      help: "Enable different season voice in Game",
      type: "Array",
      options: [
        { id: 0, label: "Random" },
        { id: 1, label: "Winter" },
        { id: 2, label: "Spring" },
        { id: 3, label: "Summer" },
        { id: 4, label: "Autumn" },
      ],
    },
    {
      id: "license",
      name: "License Message",
      help: "A server sent license.",
      type: "String",
    },
  ],
};
