export const PopnMusicOptions = {
  24: [
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "holiday_greeting",
      name: "Special Greeting",
      help: "Changes `Okay!` to a holiday greeting.",
      type: "Array",
      options: [
        { id: 0, label: "Okay!" },
        { id: 1, label: "Merry Christmas!" },
        { id: 2, label: "Happy New Year!" },
      ],
    },
  ],
  25: [
    {
      id: "force_unlock_songs",
      name: "Force Song Unlock",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "navikun_phase",
      name: "NAVI-Kun Event Phase",
      help: "NAVI-Kun event phase for all players.",
      type: "Array",
      options: [
        { id: 15, label: "Phase 1" },
        { id: 16, label: "Phase 2" },
        { id: 17, label: "Phase 3" },
        { id: 18, label: "Phase 4" },
        { id: 19, label: "Phase 5" },
        { id: 20, label: "Phase 6" },
        { id: 21, label: "Phase 7" },
        { id: 22, label: "Phase 8" },
        { id: 23, label: "Phase 9" },
        { id: 24, label: "Phase 10" },
        { id: 25, label: "Phase 11" },
        { id: 26, label: "Phase 12" },
        { id: 27, label: "Phase 13" },
        { id: 28, label: "Phase 14" },
        { id: 29, label: "Phase 15" },
        { id: 30, label: "Phase MAX" },
      ],
    },
    {
      id: "holiday_greeting",
      name: "Holiday Greeting",
      help: "Changes the payment selection confirmation sound.",
      type: "Array",
      options: [
        { id: 0, label: "Okay!" },
        { id: 1, label: "Merry Christmas!" },
        { id: 2, label: "Happy New Year!" },
      ],
    },
    {
      id: "event_archive_phase",
      name: "Event Archive Phase",
      help: "Event Archive mini-game phase for all players.",
      type: "Array",
      options: [
        { id: 0, label: "Event Archive disabled" },
        { id: 1, label: "pop'n music 11 - The Latest Space Station" },
        {
          id: 2,
          label:
            "pop'n music 11 & 12 Iroha - The Southernmost Point of the Universe / Ninja Otasuke Cheat Sheet in Trouble",
        },
        {
          id: 3,
          label: "pop'n music Sunny Park - I Love Walking in Happiness Park",
        },
        { id: 4, label: "pop'n music 12 Iroha - Ninja Code: April 1st Volume" },
        { id: 5, label: "pop'n music 15 ADVENTURE - Route to Awaken the Soul" },
        { id: 6, label: "pop'n music 20 fantasia - A Braided Fantasy Song" },
        { id: 7, label: "EXTRA" },
        {
          id: 8,
          label: "pop'n music 15 ADVENTURE - A Route with a Faint Bell Sound",
        },
        { id: 9, label: "pop'n music 13 Carnival - Bunny Magician Attraction" },
        {
          id: 10,
          label: "pop'n music 14 FEVER! - That Burning Special Attack, again!",
        },
        { id: 11, label: "pop'n music Sunny Park - Festival Nightfall Park" },
        {
          id: 12,
          label:
            "pop'n music 20 fantasia - A Fantasy Song by the Bladed Warrior",
        },
        {
          id: 13,
          label:
            "pop'n music 19 TUNE STREET - A Town Where the Sound of the Brass Band Rings After School",
        },
        { id: 14, label: "pop'n music éclale - Fun Rag Hour" },
        { id: 15, label: "pop'n music 13 Carnival - Ghost Piano Attraction" },
        {
          id: 16,
          label: "pop'n music 14 FEVER! - That Warrior Defending Peace, again!",
        },
        {
          id: 17,
          label:
            "pop'n music 18 Sengoku Retsuden - A Territory with a Glamorous Cultural Flavor",
        },
        {
          id: 18,
          label: "pop'n music éclale - Runaway Guitarist in the Starry Sky",
        },
        {
          id: 19,
          label:
            "pop'n music 17 THE MOVIE - A Blockbuster Uncovering a Conspiracy in the Peaceful City",
        },
        { id: 20, label: "pop'n music lapistoria - God's Forgotten Things" },
      ],
    },
  ],
  26: [
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "holiday_greeting",
      name: "Special Greeting",
      help: "Changes `Okay!` to a holiday greeting.",
      type: "Array",
      options: [
        { id: 0, label: "Okay!" },
        { id: 1, label: "Merry Christmas!" },
        { id: 2, label: "Happy New Year!" },
      ],
    },
  ],
  27: [
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "holiday_greeting",
      name: "Special Greeting",
      help: "Changes `Okay!` to a holiday greeting.",
      type: "Array",
      options: [
        { id: 0, label: "Okay!" },
        { id: 1, label: "Merry Christmas!" },
        { id: 2, label: "Happy New Year!" },
      ],
    },
  ],
  28: [
    {
      id: "force_unlock_decopa_method",
      name: "Deco Part Force Unlock",
      help: "Force unlock decopa for all players. Unilab decopa are unavailable through normal play.",
      type: "Array",
      options: [
        { id: 0, label: "None" },
        { id: 1, label: "Unilab Decopa Only" },
        { id: 2, label: "Unilab + Neon Lamp Decopa" },
        { id: 3, label: "Unilab + Neon Lamp + Working Cat Decopa (ALL)" },
      ],
    },
    {
      id: "force_unlock_songs",
      name: "Force Song Unlock",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_perfect_eater",
      name: "Unlock KAC Qualifier (パーフェクトイーター)",
      help: "Force unlock Perfect Eater for all players.",
      type: "Boolean",
    },
    {
      id: "music_phase",
      name: "Music Open Phase",
      help: "Default music phase for all players.",
      type: "Array",
      options: [
        { id: 0, label: "No phase unlocks" },
        { id: 7, label: "Phase 1" },
        { id: 8, label: "Phase 2" },
        { id: 9, label: "Phase 3" },
        { id: 10, label: "Phase 4" },
        { id: 11, label: "Phase 5" },
        { id: 12, label: "Phase 6" },
        { id: 13, label: "Phase 7" },
        { id: 14, label: "Phase 8" },
      ],
    },
    {
      id: "poppin_burger",
      name: "Poppin' Burger",
      help: "Poppin' Burger for all players.",
      type: "Array",
      options: [
        { id: 0, label: "Disabled" },
        { id: 1, label: "Saturday's Reward" },
        { id: 2, label: "ペパーミントは私の敵 (UPPER)" },
        { id: 3, label: "Surfing Area51" },
        { id: 4, label: "Electronic or Treat! (UPPER)" },
        { id: 5, label: "ハートのフリット" },
        { id: 6, label: "なまいきプリンセス (UPPER)" },
        { id: 7, label: "DOKIDOKI☆シューティングスター" },
        { id: 8, label: "轟け！恋のビーンボール！！ (STARDOM Remix)" },
        { id: 9, label: "Cookie Bouquets / Moving on / ANEMONE" },
        { id: 10, label: "Yum Yum OYACHU" },
        { id: 11, label: "POLꓘAMAИIA / 乱膳の舞姫" },
        { id: 12, label: "あるビー！ feat.ころねぽち / No Border" },
        { id: 13, label: "Amazing Bomberman" },
        { id: 14, label: "ミラクル☆喫茶" },
        { id: 15, label: "キセキはじまり☆ (UPPER)" },
        { id: 16, label: "astral_dismantle" },
        { id: 17, label: "まっぷたツートンソウル" },
        { id: 18, label: "そして惨劇は灰色に踊る" },
        { id: 19, label: "Hold the Pickles!!" },
        { id: 20, label: "竜を狩る者" },
        { id: 21, label: "すすめ!キッチンカー" },
        { id: 22, label: "Little Rock Overture (UPPER)" },
        { id: 23, label: "ホットドッグドカぐいレース!!!!" },
        { id: 24, label: "エトランジェ" },
        { id: 25, label: "Primitive Whimsical Chopped Salad" },
        { id: 26, label: "Rushiest Rush" },
        { id: 27, label: "MAX KARAI" },
        { id: 28, label: "cobalt (UPPER)" },
        { id: 29, label: "ONYX" },
        { id: 30, label: "Flower-Band ver.-" },
        { id: 31, label: "黒紅掬い" },
        { id: 32, label: "Viden" },
        { id: 33, label: "円環のヴァルキュリア -lopulla tragedia-" },
        { id: 34, label: "嵐の唄" },
        { id: 35, label: "pandora-追憶の彼方へ-" },
        { id: 36, label: "Dawn Saga" },
        { id: 37, label: "Yuni's Nocturnal Days" },
        { id: 38, label: "アルファ・スカイ" },
        { id: 39, label: "AVEL" },
        { id: 40, label: "MAX LOVE - 鐘の音が止む前に -" },
        { id: 41, label: "Twinkle Wonderland -Sparkle Wonderland-" },
        { id: 42, label: "It's my Miracle" },
        { id: 43, label: "昏き甲鉄のヴェルガ" },
        { id: 44, label: "Step forward" },
        { id: 45, label: "Follow Tomorrow -fleufleu Edition-" },
        { id: 46, label: "High & Low" },
        { id: 47, label: "BLAKE" },
        { id: 48, label: "零と弌の鍵の唄 (UPPER) / 走れメロンパン (UPPER)" },
        { id: 49, label: "THX 4" },
      ],
    },
    {
      id: "narunaru_puchi",
      name: "Naru Naru♪ UniLab Petit Laboratory",
      help: "Naru Naru♪ UniLab Petit Laboratory for all players.",
      type: "Array",
      options: [
        { id: 0, label: "Disabled" },
        { id: 1, label: "Naru Naru♪ UniLab Petit Laboratory" },
        { id: 2, label: "Naru Naru♪ UniLab Petit Laboratory MAX" },
      ],
    },
    {
      id: "kakusei_puchi",
      name: "Kakusei no Elem Petit",
      help: "Kakusei no Elem Petit for all players.",
      type: "Array",
      options: [
        { id: 0, label: "Disabled" },
        { id: 1, label: "Wave 1" },
        { id: 2, label: "Wave 2" },
        { id: 3, label: "Wave FINAL" },
      ],
    },
    {
      id: "toppings_boost",
      name: "Toppings Boost",
      help: "Golden Week Fair / Halloween Fair Toppings Boost for all players.",
      type: "Array",
      options: [
        { id: 0, label: "Disabled" },
        { id: 1, label: "Golden Week Boost" },
        { id: 2, label: "Halloween Boost" },
      ],
    },
    {
      id: "shigoto_neko",
      name: "Working Cat x Pop'n Music Deco Part Campaign",
      help: "Working Cat x Pop'n Music Deco Part Campaign for all players.",
      type: "Array",
      options: [
        { id: 0, label: "Disabled" },
        { id: 1, label: "Wave 1" },
        { id: 2, label: "Wave 2" },
        { id: 3, label: "Complete" },
      ],
    },
  ],
};
