export const SDVXOptions = {
  1: [
    {
      id: "disable_matching",
      name: "Disable Online Matching",
      help: "Saves time in game, no waiting.",
      type: "Boolean",
    },
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_cards",
      name: "Force Unlock Appeal Cards",
      help: "Force unlock all appeal cards.",
      type: "Boolean",
    },
  ],
  2: [
    {
      id: "disable_matching",
      name: "Disable Online Matching",
      help: "Saves time in game, no waiting.",
      type: "Boolean",
    },
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_cards",
      name: "Force Unlock Appeal Cards",
      help: "Force unlock all appeal cards.",
      type: "Boolean",
    },
    {
      id: "maxima",
      name: "MAXIMA Nav",
      help: "Replaces Rasis with MAXIMA in menus.",
      type: "Boolean",
    },
    {
      id: "bemani_stadium",
      name: "BEMANI Event Phase",
      help: "Sets the BEMANI Event Phase.",
      type: "Array",
      options: [
        { id: 0, label: "No Event" },
        { id: 1, label: "BEMANI STADIUM" },
        { id: 2, label: "Bemani Ruins" },
      ],
    },
  ],
  3: [
    {
      id: "disable_matching",
      name: "Disable Online Matching",
      help: "Saves time in game, no waiting.",
      type: "Boolean",
    },
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_cards",
      name: "Force Unlock Appeal Cards",
      help: "Force unlock all appeal cards.",
      type: "Boolean",
    },
    {
      id: "force_unlock_crew",
      name: "Force Unlock Crew Cards",
      help: "Force unlock all crew and sub-crew cards.",
      type: "Boolean",
    },
    {
      id: "enable_story",
      name: "Enable Story Mode",
      help: "Enables all story modes episodes for all players.",
      type: "Boolean",
    },
  ],
  4: [
    {
      id: "disable_matching",
      name: "Disable Online Matching",
      help: "Saves time in game, no waiting.",
      type: "Boolean",
    },
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_cards",
      name: "Force Unlock Appeal Cards",
      help: "Force unlock all appeal cards.",
      type: "Boolean",
    },
    {
      id: "force_unlock_crew",
      name: "Force Unlock Crew Cards",
      help: "Force unlock all crew and sub-crew cards.",
      type: "Boolean",
    },
  ],
  5: [
    {
      id: "disable_matching",
      name: "Disable Online Matching",
      help: "Saves time in game, no waiting.",
      type: "Boolean",
    },
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_cards",
      name: "Force Unlock Appeal Cards",
      help: "Force unlock all appeal cards.",
      type: "Boolean",
    },
    {
      id: "force_unlock_crew",
      name: "Force Unlock Crew Cards",
      help: "Force unlock all crew and sub-crew cards.",
      type: "Boolean",
    },
    {
      id: "chara_go1",
      name: "Game Over Character #1",
      help: "Sets a character on the Game Over screen.",
      type: "Array",
      options: [
        { id: 0, label: "Rasis" },
        { id: 1, label: "Grace" },
        { id: 2, label: "Right" },
        { id: 3, label: "Left" },
        { id: 4, label: "MAXIMA" },
        { id: 5, label: "Tsumabuki" },
      ],
    },
    {
      id: "gameover1",
      name: "Game Over Message #1",
      help: "A message that a character will say on the Game Over screen. Use \\n to create newlines.",
      type: "LargeText",
    },
    {
      id: "chara_go2",
      name: "Game Over Character #2",
      help: "Sets a character on the Game Over screen.",
      type: "Array",
      options: [
        { id: 0, label: "Rasis" },
        { id: 1, label: "Grace" },
        { id: 2, label: "Right" },
        { id: 3, label: "Left" },
        { id: 4, label: "MAXIMA" },
        { id: 5, label: "Tsumabuki" },
      ],
    },
    {
      id: "gameover2",
      name: "Game Over Message #2",
      help: "A message that a character will say on the Game Over screen. Use \\n to create newlines.",
      type: "LargeText",
    },
    {
      id: "chara_go3",
      name: "Game Over Character #3",
      help: "Sets a character on the Game Over screen.",
      type: "Array",
      options: [
        { id: 0, label: "Rasis" },
        { id: 1, label: "Grace" },
        { id: 2, label: "Right" },
        { id: 3, label: "Left" },
        { id: 4, label: "MAXIMA" },
        { id: 5, label: "Tsumabuki" },
      ],
    },
    {
      id: "gameover3",
      name: "Game Over Message #3",
      help: "A message that a character will say on the Game Over screen. Use \\n to create newlines.",
      type: "LargeText",
    },
  ],
  6: [
    {
      id: "disable_matching",
      name: "Disable Online Matching",
      help: "Saves time in game, no waiting.",
      type: "Boolean",
    },
    {
      id: "submonitor_vsync_enable",
      name: "Enable sub-screen VSYNC",
      help: "May cause performance issues when not running arcade hardware.",
      type: "Boolean",
    },
    {
      id: "use_cuda_video_presenter",
      name: "Enable CUDA engine",
      help: "May cause performance issues when not running arcade hardware.",
      type: "Boolean",
    },
    {
      id: "disable_promo",
      name: "Disable Promotional Content",
      help: "Disables any promotional content that appears on the attract screen.",
      type: "Boolean",
    },
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_cards",
      name: "Force Unlock Appeal Cards",
      help: "Force unlock all appeal cards.",
      type: "Boolean",
    },
    {
      id: "force_unlock_crew",
      name: "Force Unlock Crew Cards",
      help: "Force unlock all crew and sub-crew cards.",
      type: "Boolean",
    },
    {
      id: "force_unlock_skill",
      name: "Force Unlock Skill Analyzer Courses",
      help: "Force unlock all Skill Analyzer courses.",
      type: "Boolean",
    },
    {
      id: "active_stamp_event",
      name: "Active Stamp Event",
      help: "Select the active stamp event.\nRefer to bemaniwiki for details on each event: https://bemaniwiki.com/?SOUND+VOLTEX+EXCEED+GEAR/解禁要素#stamp_event_end",
      type: "Array",
      options: [
        { id: 0, label: "None" },
        { id: 1, label: "New Year's Stamp Bonus (2022)" },
        { id: 2, label: "HIMEHINA Collaboration Event" },
        { id: 3, label: "REFLEC BEAT Special Stamp! (Part 1)" },
        { id: 4, label: "New Year's Stamp Bonus (2023)" },
        { id: 5, label: "SOUND VOLTEX 10th Anniversary Song Stamp" },
        { id: 6, label: "PCB Refill Stamp Event" },
        { id: 7, label: "11th Anniversary Stamp" },
        { id: 8, label: "BEMANI PRO LEAGUE -SEASON 2-" },
        { id: 9, label: "KAC (2023) Special Stamps (Preliminary Round A)" },
        { id: 10, label: "KAC (2023) Special Stamps (Preliminary Round B)" },
        { id: 11, label: "New Year's Dragon Feast Stamp Bonus" },
        { id: 12, label: "12th Anniversary Stamp" },
        { id: 13, label: "BEMANI PRO LEAGUE -SEASON 3- Complete Stamp" },
        { id: 14, label: "BEMANI PRO LEAGUE -SEASON 3- Special Stamp" },
        { id: 15, label: "REFLEC BEAT Special Stamp! (Part 2)" },
        {
          id: 16,
          label: "2025 U,R,B,R,,, YE-AR---!!!ｷｬ----!!!!!! Stamp Bonus",
        },
        { id: 17, label: "13th Anniversary Stamp" },
        { id: 18, label: "PCB Refill Stamp Event (2024/2025)" },
        { id: 19, label: "hololive SUPER EXPO 2025 Collaboration Stickers!" },
        { id: 20, label: "PRECIOUS UNIVERSAL CELEBRATE Stamp" },
        { id: 21, label: "REFLEC BEAT Special Stamp! (Part 3)" },
        { id: 22, label: "GITADORA Special Stamp!" },
      ],
    },
    {
      id: "forced_event",
      name: "Force Enable Event",
      help: "Select a scheduled event to force enable.",
      type: "Array",
      options: [
        { id: 0, label: "None" },
        { id: 1, label: "Valentine's Day 2024" },
        { id: 2, label: "White Day 2024" },
        { id: 3, label: "April Fools 2025" },
        { id: 4, label: "Halloween" },
        { id: 5, label: "Christmas 2023" },
        { id: 6, label: "New Years" },
      ],
    },
    {
      id: "disable_omega",
      name: "Disable OMEGA DIMENSION",
      help: "Disables all OMEGA DIMENSION events (1 through 8)",
      type: "Boolean",
    },
    {
      id: "disable_hexa",
      name: "Disable HEXA DIVER",
      help: "Disables all Hexa Diver events.",
      type: "Boolean",
    },
    {
      id: "disable_tama",
      name: "Disable Tamaneko Adventure",
      help: "Disables the Tamaneko Adventure unlock event",
      type: "Boolean",
    },
    {
      id: "enable_konami_50th",
      name: "Enable Konami's 50th Anniversary Logo",
      help: "Force enable the Konami 50th Anniversary Logo",
      type: "Boolean",
    },
    {
      id: "chara_go1",
      name: "Game Over Character #1",
      help: "Sets a character on the Game Over screen.",
      type: "Array",
      options: [
        { id: 10000, label: "Random" },
        { id: 0, label: "Rasis" },
        { id: 1, label: "Grace" },
        { id: 2, label: "Right" },
        { id: 3, label: "Left" },
        { id: 4, label: "MAXIMA" },
        { id: 5, label: "Tsumabuki" },
        { id: 6, label: "Watagashi" },
        { id: 7, label: "Neno (April Fools)" },
        { id: 8, label: "Riot" },
        { id: 9, label: "Rex" },
        { id: 10, label: "Cannon" },
        { id: 11, label: "Ortlinde" },
        { id: 12, label: "Noisia" },
        { id: 13, label: "Hiryubiren" },
        { id: 14, label: "Neno" },
        { id: 15, label: "Miyako" },
        { id: 16, label: "Makina" },
        { id: 17, label: "Ondine" },
        { id: 18, label: "Shelly" },
        { id: 19, label: "Aria" },
        { id: 20, label: "Torako" },
        { id: 21, label: "Gemu" },
        { id: 22, label: "MAXIMA (EXCEED GEAR)" },
        { id: 23, label: "Mitsuru" },
        { id: 24, label: "Grace" },
        { id: 25, label: "Left (EXCEED GEAR)" },
        { id: 26, label: "Mai" },
        { id: 27, label: "Satan" },
        { id: 28, label: "Mimiko" },
        { id: 29, label: "Pilica" },
        { id: 30, label: "Tama" },
        { id: 31, label: "Kanade" },
        { id: 32, label: "Rowa" },
        { id: 33, label: "Setu" },
        { id: 34, label: "Grace (EXCEED GEAR)" },
        { id: 35, label: "Rasis (EXCEED GEAR)" },
        { id: 36, label: "Nathanael" },
        { id: 37, label: "Apex Sisters" },
        { id: 38, label: "Joyeuse" },
        { id: 39, label: "Wabutan" },
        { id: 40, label: "Vertex" },
        { id: 41, label: "Tsubaki" },
        { id: 42, label: "Hiyuki" },
        { id: 43, label: "Suzune" },
        { id: 44, label: "Kureha" },
        { id: 45, label: "Cawoashi" },
        { id: 46, label: "Kemuri" },
        { id: 47, label: "Apex Sisters (Chiai Abusu)" },
        { id: 48, label: "Sakurako" },
        { id: 49, label: "Apex Sisters (Doumeki Hyakki)" },
        { id: 50, label: "Haelequin" },
        { id: 51, label: "Neno (EXCEED GEAR)" },
        { id: 52, label: "Apex Sisters (Saotome Rei)" },
        { id: 53, label: "MISS.DD" },
        { id: 54, label: "Kisa" },
        { id: 55, label: "Kota" },
        { id: 56, label: "Yukito" },
        { id: 57, label: "Ichika" },
        { id: 58, label: "Left" },
        { id: 59, label: "Apex Sisters (Poroshiritake Ema)" },
        { id: 60, label: "Gin" },
        { id: 61, label: "Natsuhi" },
        { id: 62, label: "Rouge" },
        { id: 63, label: "Yuki" },
        { id: 64, label: "Yusya" },
        { id: 65, label: "Nana" },
        { id: 66, label: "Psychoholic" },
        { id: 67, label: "Toraipuru" },
        { id: 68, label: "Iruyoru" },
        { id: 69, label: "Rishna" },
        { id: 70, label: "Bansui" },
        { id: 71, label: "Soul" },
        { id: 72, label: "Rimuru" },
        { id: 73, label: "Profession" },
        { id: 74, label: "Kokona" },
        { id: 75, label: "Chocopla" },
        { id: 76, label: "Inoten" },
        { id: 77, label: "Haruka" },
        { id: 78, label: "Dee" },
        { id: 79, label: "Konoha" },
        { id: 80, label: "Right (EXCEED GEAR)" },
        { id: 81, label: "Esp" },
        { id: 82, label: "Mitsuruco" },
        { id: 83, label: "Lyonel" },
        { id: 84, label: "Vita" },
        { id: 85, label: "Rain" },
        { id: 86, label: "Natsuhi (2)" },
        { id: 87, label: "Ruki" },
        { id: 88, label: "Ekusa" },
        { id: 89, label: "Kino" },
        { id: 90, label: "Mion" },
        { id: 91, label: "Etoile" },
        { id: 92, label: "Chinema" },
        { id: 93, label: "Capsaicin" },
        { id: 94, label: "Rain02" },
        { id: 95, label: "Flowry" },
        { id: 96, label: "Vela" },
        { id: 97, label: "Hotaru" },
        { id: 98, label: "Kokona (2)" },
        { id: 99, label: "Pannakotta" },
        { id: 100, label: "Madholic" },
        { id: 101, label: "MAXIMA (April Fools)" },
        { id: 102, label: "Hero" },
        { id: 103, label: "Fukuryu" },
        { id: 104, label: "Pico" },
        { id: 105, label: "Nishinippori" },
        { id: 106, label: "Bof" },
        { id: 107, label: "Fluorine" },
        { id: 108, label: "Kouki" },
        { id: 109, label: "Yutanike" },
        { id: 110, label: "Ribbon" },
        { id: 111, label: "Saigawara" },
        { id: 112, label: "Chikage" },
        { id: 113, label: "Candy" },
        { id: 114, label: "Rasis (April Fools)" },
        { id: 115, label: "Kamito" },
        { id: 116, label: "Cat" },
        { id: 117, label: "Grace (April Fools)" },
        { id: 118, label: "Wanlove" },
        { id: 119, label: "Left (April Fools)" },
        { id: 120, label: "Right (April Fools)" },
        { id: 121, label: "Gorilla" },
        { id: 122, label: "Akane" },
        { id: 123, label: "Tsumabuki (EXCEED GEAR)" },
        { id: 124, label: "Evileye" },
        { id: 125, label: "Tamaneko" },
        { id: 126, label: "Gangara" },
      ],
    },
    {
      id: "gameover1",
      name: "Game Over Message #1",
      help: "A message that a character will say on the Game Over screen. Use \\n to create newlines.",
      type: "LargeText",
    },
    {
      id: "chara_go2",
      name: "Game Over Character #2",
      help: "Sets a character on the Game Over screen.",
      type: "Array",
      options: [
        { id: 10000, label: "Random" },
        { id: 0, label: "Rasis" },
        { id: 1, label: "Grace" },
        { id: 2, label: "Right" },
        { id: 3, label: "Left" },
        { id: 4, label: "MAXIMA" },
        { id: 5, label: "Tsumabuki" },
        { id: 6, label: "Watagashi" },
        { id: 7, label: "Neno (April Fools)" },
        { id: 8, label: "Riot" },
        { id: 9, label: "Rex" },
        { id: 10, label: "Cannon" },
        { id: 11, label: "Ortlinde" },
        { id: 12, label: "Noisia" },
        { id: 13, label: "Hiryubiren" },
        { id: 14, label: "Neno" },
        { id: 15, label: "Miyako" },
        { id: 16, label: "Makina" },
        { id: 17, label: "Ondine" },
        { id: 18, label: "Shelly" },
        { id: 19, label: "Aria" },
        { id: 20, label: "Torako" },
        { id: 21, label: "Gemu" },
        { id: 22, label: "MAXIMA (EXCEED GEAR)" },
        { id: 23, label: "Mitsuru" },
        { id: 24, label: "Grace" },
        { id: 25, label: "Left (EXCEED GEAR)" },
        { id: 26, label: "Mai" },
        { id: 27, label: "Satan" },
        { id: 28, label: "Mimiko" },
        { id: 29, label: "Pilica" },
        { id: 30, label: "Tama" },
        { id: 31, label: "Kanade" },
        { id: 32, label: "Rowa" },
        { id: 33, label: "Setu" },
        { id: 34, label: "Grace (EXCEED GEAR)" },
        { id: 35, label: "Rasis (EXCEED GEAR)" },
        { id: 36, label: "Nathanael" },
        { id: 37, label: "Apex Sisters" },
        { id: 38, label: "Joyeuse" },
        { id: 39, label: "Wabutan" },
        { id: 40, label: "Vertex" },
        { id: 41, label: "Tsubaki" },
        { id: 42, label: "Hiyuki" },
        { id: 43, label: "Suzune" },
        { id: 44, label: "Kureha" },
        { id: 45, label: "Cawoashi" },
        { id: 46, label: "Kemuri" },
        { id: 47, label: "Apex Sisters (Chiai Abusu)" },
        { id: 48, label: "Sakurako" },
        { id: 49, label: "Apex Sisters (Doumeki Hyakki)" },
        { id: 50, label: "Haelequin" },
        { id: 51, label: "Neno (EXCEED GEAR)" },
        { id: 52, label: "Apex Sisters (Saotome Rei)" },
        { id: 53, label: "MISS.DD" },
        { id: 54, label: "Kisa" },
        { id: 55, label: "Kota" },
        { id: 56, label: "Yukito" },
        { id: 57, label: "Ichika" },
        { id: 58, label: "Left" },
        { id: 59, label: "Apex Sisters (Poroshiritake Ema)" },
        { id: 60, label: "Gin" },
        { id: 61, label: "Natsuhi" },
        { id: 62, label: "Rouge" },
        { id: 63, label: "Yuki" },
        { id: 64, label: "Yusya" },
        { id: 65, label: "Nana" },
        { id: 66, label: "Psychoholic" },
        { id: 67, label: "Toraipuru" },
        { id: 68, label: "Iruyoru" },
        { id: 69, label: "Rishna" },
        { id: 70, label: "Bansui" },
        { id: 71, label: "Soul" },
        { id: 72, label: "Rimuru" },
        { id: 73, label: "Profession" },
        { id: 74, label: "Kokona" },
        { id: 75, label: "Chocopla" },
        { id: 76, label: "Inoten" },
        { id: 77, label: "Haruka" },
        { id: 78, label: "Dee" },
        { id: 79, label: "Konoha" },
        { id: 80, label: "Right (EXCEED GEAR)" },
        { id: 81, label: "Esp" },
        { id: 82, label: "Mitsuruco" },
        { id: 83, label: "Lyonel" },
        { id: 84, label: "Vita" },
        { id: 85, label: "Rain" },
        { id: 86, label: "Natsuhi (2)" },
        { id: 87, label: "Ruki" },
        { id: 88, label: "Ekusa" },
        { id: 89, label: "Kino" },
        { id: 90, label: "Mion" },
        { id: 91, label: "Etoile" },
        { id: 92, label: "Chinema" },
        { id: 93, label: "Capsaicin" },
        { id: 94, label: "Rain02" },
        { id: 95, label: "Flowry" },
        { id: 96, label: "Vela" },
        { id: 97, label: "Hotaru" },
        { id: 98, label: "Kokona (2)" },
        { id: 99, label: "Pannakotta" },
        { id: 100, label: "Madholic" },
        { id: 101, label: "MAXIMA (April Fools)" },
        { id: 102, label: "Hero" },
        { id: 103, label: "Fukuryu" },
        { id: 104, label: "Pico" },
        { id: 105, label: "Nishinippori" },
        { id: 106, label: "Bof" },
        { id: 107, label: "Fluorine" },
        { id: 108, label: "Kouki" },
        { id: 109, label: "Yutanike" },
        { id: 110, label: "Ribbon" },
        { id: 111, label: "Saigawara" },
        { id: 112, label: "Chikage" },
        { id: 113, label: "Candy" },
        { id: 114, label: "Rasis (April Fools)" },
        { id: 115, label: "Kamito" },
        { id: 116, label: "Cat" },
        { id: 117, label: "Grace (April Fools)" },
        { id: 118, label: "Wanlove" },
        { id: 119, label: "Left (April Fools)" },
        { id: 120, label: "Right (April Fools)" },
        { id: 121, label: "Gorilla" },
        { id: 122, label: "Akane" },
        { id: 123, label: "Tsumabuki (EXCEED GEAR)" },
        { id: 124, label: "Evileye" },
        { id: 125, label: "Tamaneko" },
        { id: 126, label: "Gangara" },
      ],
    },
    {
      id: "gameover2",
      name: "Game Over Message #2",
      help: "A message that a character will say on the Game Over screen. Use \\n to create newlines.",
      type: "LargeText",
    },
    {
      id: "chara_go3",
      name: "Game Over Character #3",
      help: "Sets a character on the Game Over screen.",
      type: "Array",
      options: [
        { id: 10000, label: "Random" },
        { id: 0, label: "Rasis" },
        { id: 1, label: "Grace" },
        { id: 2, label: "Right" },
        { id: 3, label: "Left" },
        { id: 4, label: "MAXIMA" },
        { id: 5, label: "Tsumabuki" },
        { id: 6, label: "Watagashi" },
        { id: 7, label: "Neno (April Fools)" },
        { id: 8, label: "Riot" },
        { id: 9, label: "Rex" },
        { id: 10, label: "Cannon" },
        { id: 11, label: "Ortlinde" },
        { id: 12, label: "Noisia" },
        { id: 13, label: "Hiryubiren" },
        { id: 14, label: "Neno" },
        { id: 15, label: "Miyako" },
        { id: 16, label: "Makina" },
        { id: 17, label: "Ondine" },
        { id: 18, label: "Shelly" },
        { id: 19, label: "Aria" },
        { id: 20, label: "Torako" },
        { id: 21, label: "Gemu" },
        { id: 22, label: "MAXIMA (EXCEED GEAR)" },
        { id: 23, label: "Mitsuru" },
        { id: 24, label: "Grace" },
        { id: 25, label: "Left (EXCEED GEAR)" },
        { id: 26, label: "Mai" },
        { id: 27, label: "Satan" },
        { id: 28, label: "Mimiko" },
        { id: 29, label: "Pilica" },
        { id: 30, label: "Tama" },
        { id: 31, label: "Kanade" },
        { id: 32, label: "Rowa" },
        { id: 33, label: "Setu" },
        { id: 34, label: "Grace (EXCEED GEAR)" },
        { id: 35, label: "Rasis (EXCEED GEAR)" },
        { id: 36, label: "Nathanael" },
        { id: 37, label: "Apex Sisters" },
        { id: 38, label: "Joyeuse" },
        { id: 39, label: "Wabutan" },
        { id: 40, label: "Vertex" },
        { id: 41, label: "Tsubaki" },
        { id: 42, label: "Hiyuki" },
        { id: 43, label: "Suzune" },
        { id: 44, label: "Kureha" },
        { id: 45, label: "Cawoashi" },
        { id: 46, label: "Kemuri" },
        { id: 47, label: "Apex Sisters (Chiai Abusu)" },
        { id: 48, label: "Sakurako" },
        { id: 49, label: "Apex Sisters (Doumeki Hyakki)" },
        { id: 50, label: "Haelequin" },
        { id: 51, label: "Neno (EXCEED GEAR)" },
        { id: 52, label: "Apex Sisters (Saotome Rei)" },
        { id: 53, label: "MISS.DD" },
        { id: 54, label: "Kisa" },
        { id: 55, label: "Kota" },
        { id: 56, label: "Yukito" },
        { id: 57, label: "Ichika" },
        { id: 58, label: "Left" },
        { id: 59, label: "Apex Sisters (Poroshiritake Ema)" },
        { id: 60, label: "Gin" },
        { id: 61, label: "Natsuhi" },
        { id: 62, label: "Rouge" },
        { id: 63, label: "Yuki" },
        { id: 64, label: "Yusya" },
        { id: 65, label: "Nana" },
        { id: 66, label: "Psychoholic" },
        { id: 67, label: "Toraipuru" },
        { id: 68, label: "Iruyoru" },
        { id: 69, label: "Rishna" },
        { id: 70, label: "Bansui" },
        { id: 71, label: "Soul" },
        { id: 72, label: "Rimuru" },
        { id: 73, label: "Profession" },
        { id: 74, label: "Kokona" },
        { id: 75, label: "Chocopla" },
        { id: 76, label: "Inoten" },
        { id: 77, label: "Haruka" },
        { id: 78, label: "Dee" },
        { id: 79, label: "Konoha" },
        { id: 80, label: "Right (EXCEED GEAR)" },
        { id: 81, label: "Esp" },
        { id: 82, label: "Mitsuruco" },
        { id: 83, label: "Lyonel" },
        { id: 84, label: "Vita" },
        { id: 85, label: "Rain" },
        { id: 86, label: "Natsuhi (2)" },
        { id: 87, label: "Ruki" },
        { id: 88, label: "Ekusa" },
        { id: 89, label: "Kino" },
        { id: 90, label: "Mion" },
        { id: 91, label: "Etoile" },
        { id: 92, label: "Chinema" },
        { id: 93, label: "Capsaicin" },
        { id: 94, label: "Rain02" },
        { id: 95, label: "Flowry" },
        { id: 96, label: "Vela" },
        { id: 97, label: "Hotaru" },
        { id: 98, label: "Kokona (2)" },
        { id: 99, label: "Pannakotta" },
        { id: 100, label: "Madholic" },
        { id: 101, label: "MAXIMA (April Fools)" },
        { id: 102, label: "Hero" },
        { id: 103, label: "Fukuryu" },
        { id: 104, label: "Pico" },
        { id: 105, label: "Nishinippori" },
        { id: 106, label: "Bof" },
        { id: 107, label: "Fluorine" },
        { id: 108, label: "Kouki" },
        { id: 109, label: "Yutanike" },
        { id: 110, label: "Ribbon" },
        { id: 111, label: "Saigawara" },
        { id: 112, label: "Chikage" },
        { id: 113, label: "Candy" },
        { id: 114, label: "Rasis (April Fools)" },
        { id: 115, label: "Kamito" },
        { id: 116, label: "Cat" },
        { id: 117, label: "Grace (April Fools)" },
        { id: 118, label: "Wanlove" },
        { id: 119, label: "Left (April Fools)" },
        { id: 120, label: "Right (April Fools)" },
        { id: 121, label: "Gorilla" },
        { id: 122, label: "Akane" },
        { id: 123, label: "Tsumabuki (EXCEED GEAR)" },
        { id: 124, label: "Evileye" },
        { id: 125, label: "Tamaneko" },
        { id: 126, label: "Gangara" },
      ],
    },
    {
      id: "gameover3",
      name: "Game Over Message #3",
      help: "A message that a character will say on the Game Over screen. Use \\n to create newlines.",
      type: "LargeText",
    },
  ],
};
