export const SDVXOptions = {
  1: [
    {
      id: "disable_matching",
      name: "Disable Online Matching",
      help: "Saves time in game, no waiting.",
      type: "Boolean",
    },
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_cards",
      name: "Force Unlock Appeal Cards",
      help: "Force unlock all appeal cards.",
      type: "Boolean",
    },
  ],
  2: [
    {
      id: "disable_matching",
      name: "Disable Online Matching",
      help: "Saves time in game, no waiting.",
      type: "Boolean",
    },
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_cards",
      name: "Force Unlock Appeal Cards",
      help: "Force unlock all appeal cards.",
      type: "Boolean",
    },
    {
      id: "maxima",
      name: "MAXIMA Nav",
      help: "Replaces Rasis with MAXIMA in menus.",
      type: "Boolean",
    },
    {
      id: "bemani_stadium",
      name: "BEMANI Event Phase",
      help: "Sets the BEMANI Event Phase.",
      type: "Array",
      options: [
        { id: 0, label: "No Event" },
        { id: 1, label: "BEMANI STADIUM" },
        { id: 2, label: "Bemani Ruins" },
      ],
    },
  ],
  3: [
    {
      id: "disable_matching",
      name: "Disable Online Matching",
      help: "Saves time in game, no waiting.",
      type: "Boolean",
    },
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_cards",
      name: "Force Unlock Appeal Cards",
      help: "Force unlock all appeal cards.",
      type: "Boolean",
    },
    {
      id: "force_unlock_crew",
      name: "Force Unlock Crew Cards",
      help: "Force unlock all crew and sub-crew cards.",
      type: "Boolean",
    },
    {
      id: "enable_story",
      name: "Enable Story Mode",
      help: "Enables all story modes episodes for all players.",
      type: "Boolean",
    },
  ],
  4: [
    {
      id: "disable_matching",
      name: "Disable Online Matching",
      help: "Saves time in game, no waiting.",
      type: "Boolean",
    },
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_cards",
      name: "Force Unlock Appeal Cards",
      help: "Force unlock all appeal cards.",
      type: "Boolean",
    },
    {
      id: "force_unlock_crew",
      name: "Force Unlock Crew Cards",
      help: "Force unlock all crew and sub-crew cards.",
      type: "Boolean",
    },
  ],
  5: [
    {
      id: "disable_matching",
      name: "Disable Online Matching",
      help: "Saves time in game, no waiting.",
      type: "Boolean",
    },
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_cards",
      name: "Force Unlock Appeal Cards",
      help: "Force unlock all appeal cards.",
      type: "Boolean",
    },
    {
      id: "force_unlock_crew",
      name: "Force Unlock Crew Cards",
      help: "Force unlock all crew and sub-crew cards.",
      type: "Boolean",
    },
    {
      id: "chara_go1",
      name: "Game Over Character #1",
      help: "Sets a character on the Game Over screen.",
      type: "Array",
      options: [
        { id: 0, label: "Rasis" },
        { id: 1, label: "Grace" },
        { id: 2, label: "Right" },
        { id: 3, label: "Left" },
        { id: 4, label: "MAXIMA" },
        { id: 5, label: "Tsumabuki" },
      ],
    },
    {
      id: "gameover1",
      name: "Game Over Message #1",
      help: "A message that a character will say on the Game Over screen. Use \\n to create newlines.",
      type: "LargeText",
    },
    {
      id: "chara_go2",
      name: "Game Over Character #2",
      help: "Sets a character on the Game Over screen.",
      type: "Array",
      options: [
        { id: 0, label: "Rasis" },
        { id: 1, label: "Grace" },
        { id: 2, label: "Right" },
        { id: 3, label: "Left" },
        { id: 4, label: "MAXIMA" },
        { id: 5, label: "Tsumabuki" },
      ],
    },
    {
      id: "gameover2",
      name: "Game Over Message #2",
      help: "A message that a character will say on the Game Over screen. Use \\n to create newlines.",
      type: "LargeText",
    },
    {
      id: "chara_go3",
      name: "Game Over Character #3",
      help: "Sets a character on the Game Over screen.",
      type: "Array",
      options: [
        { id: 0, label: "Rasis" },
        { id: 1, label: "Grace" },
        { id: 2, label: "Right" },
        { id: 3, label: "Left" },
        { id: 4, label: "MAXIMA" },
        { id: 5, label: "Tsumabuki" },
      ],
    },
    {
      id: "gameover3",
      name: "Game Over Message #3",
      help: "A message that a character will say on the Game Over screen. Use \\n to create newlines.",
      type: "LargeText",
    },
  ],
  6: [
    {
      id: "disable_matching",
      name: "Disable Online Matching",
      help: "Saves time in game, no waiting.",
      type: "Boolean",
    },
    {
      id: "force_unlock_songs",
      name: "Force Unlock Songs",
      help: "Force unlock all songs.",
      type: "Boolean",
    },
    {
      id: "force_unlock_cards",
      name: "Force Unlock Appeal Cards",
      help: "Force unlock all appeal cards.",
      type: "Boolean",
    },
    {
      id: "force_unlock_crew",
      name: "Force Unlock Crew Cards",
      help: "Force unlock all crew and sub-crew cards.",
      type: "Boolean",
    },
    {
      id: "disable_omega",
      name: "Disable OMEGA DIMENSION",
      help: "Disables all OMEGA DIMENSION events (1 through 8)",
      type: "Boolean",
    },
    {
      id: "disable_hexa",
      name: "Disable HEXA DIVER",
      help: "Disables all Hexa Diver events.",
      type: "Boolean",
    },
    {
      id: "chara_go1",
      name: "Game Over Character #1",
      help: "Sets a character on the Game Over screen.",
      type: "Array",
      options: [
        { id: 0, label: "Rasis" },
        { id: 1, label: "Grace" },
        { id: 2, label: "Right" },
        { id: 3, label: "Left" },
        { id: 4, label: "MAXIMA" },
        { id: 5, label: "Tsumabuki" },
      ],
    },
    {
      id: "gameover1",
      name: "Game Over Message #1",
      help: "A message that a character will say on the Game Over screen. Use \\n to create newlines.",
      type: "LargeText",
    },
    {
      id: "chara_go2",
      name: "Game Over Character #2",
      help: "Sets a character on the Game Over screen.",
      type: "Array",
      options: [
        { id: 0, label: "Rasis" },
        { id: 1, label: "Grace" },
        { id: 2, label: "Right" },
        { id: 3, label: "Left" },
        { id: 4, label: "MAXIMA" },
        { id: 5, label: "Tsumabuki" },
      ],
    },
    {
      id: "gameover2",
      name: "Game Over Message #2",
      help: "A message that a character will say on the Game Over screen. Use \\n to create newlines.",
      type: "LargeText",
    },
    {
      id: "chara_go3",
      name: "Game Over Character #3",
      help: "Sets a character on the Game Over screen.",
      type: "Array",
      options: [
        { id: 0, label: "Rasis" },
        { id: 1, label: "Grace" },
        { id: 2, label: "Right" },
        { id: 3, label: "Left" },
        { id: 4, label: "MAXIMA" },
        { id: 5, label: "Tsumabuki" },
      ],
    },
    {
      id: "gameover3",
      name: "Game Over Message #3",
      help: "A message that a character will say on the Game Over screen. Use \\n to create newlines.",
      type: "LargeText",
    },
  ],
};
